### ISSUE TITLE
[Bug] withPrefabValuesForField() throws for fields declaring interfaces and super-types

### ISSUE THREAD

**Issue by Vankog** [jqno/equalsverifier#1012]
### Describe the bug

`withPrefabValuesForField()` throws precondition exception for interface fields (e.g. `java.util.List`) if prefab values are interface-implementations or sub-implementations of the defined field type.
e.g. for `List` it fails for: 
* `java.util.ArrayList`
* `java.util.Arrays.ArrayList` via `java.util.Arrays.asList(T...)`
* `java.util.Collections.SingletonList`, created via `java.util.Collections.singletonList(T)`

### Steps to reproduce

1. Create a POJO with an interface, e.g. `java.util.List` field.
1. Test POJO with  
`.withPrefabValues(List.class, Collections.singletonList(red), Collections.singletonList(blue))`
   * works☑️
1. Test POJO with  
`.withPrefabValuesForField("myListField", Collections.singletonList(red), Collections.singletonList(blue))`
   * fails❌
1. Test POJO with  
`.withPrefabValuesForField("myListField", Arrays.asList(red), Arrays.asList(blue))`
   * fails❌
1. Test POJO with  
`.withPrefabValuesForField("myListField", Collections.unmodifiableList(Arrays.asList(red)), Collections.unmodifiableList(Arrays.asList(blue)))`
   * fails❌

### Error message and version number

EqualsVerifier v. 3.17.1
JDK 8 Temurin

```txt
java.lang.IllegalStateException: Precondition: Prefab values for field subItems should be of type List but are SingletonList.
	at nl.jqno.equalsverifier.internal.util.Validations.validate(Validations.java:270)
	at nl.jqno.equalsverifier.internal.util.Validations.validateFieldTypeMatches(Validations.java:103)
	at nl.jqno.equalsverifier.internal.util.PrefabValuesApi.addPrefabValuesForField(PrefabValuesApi.java:51)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.withPrefabValuesForField(SingleTypeEqualsVerifierApi.java:146)
	at my.test.DummyClassTest.testEqualsContract(ItemDataTest.java:27)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

### Code: EqualsVerifier invocation

```java
        EqualsVerifier.forClass(DummyClass.class)
                      .suppress(Warning.NONFINAL_FIELDS, Warning.STRICT_INHERITANCE)
                      .withPrefabValuesForField("myListField", Collections.singletonList(red), Collections.singletonList(blue))
                      .verify();
```

### Code: class under test

```java
public class DummyClass {
    String id;
    List<String> myListField;
    /* ...equals / hashcode... */
}
```

### Additional context

Using the old  
`.withPrefabValues(List.class, Collections.singletonList(red), Collections.singletonList(blue))`
works.  
Thus, the expectation is that it works for `withPrefabValuesForField()` as well.

EDIT: 
Looking at [nl.jqno.equalsverifier.internal.util.Validations.validateFieldTypeMatches(Class<T>, String, Class<?>)](https://github.com/jqno/equalsverifier/blob/fb2cd1a0e20cfb7b3d0e2dba103807d382066a76/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/util/Validations.java#L98) indicates that this happens with all type hierarchies, as the code uses
`boolean sameFields = f.getType().equals(fieldType);`
enforcing an exact type match, doesn't it?

EDIT 2: Yes, testing implies that also type hierarchies are affected.  
I tested it against a field of type `java.lang.Object` with any sub-type as prefab values.

**Comment by Vankog** [comment]
The solution might probably, to use `java.lang.Class.isAssignableFrom(Class<?>)`

**Comment by jqno** [comment]
You're completely right. Thanks for the elaborate report, this made it very easy for me to make the fix.

Version 3.17.2 is now syncing with Maven Central!

**Comment by Vankog** [comment]
Oh, I was too slow ^^
Well, maybe the test helps nonetheless.
