### ISSUE TITLE
CachedHashCodeInitializer does not support protected or package-local cachedHashCode

### ISSUE THREAD

**Issue by npgall** [jqno/equalsverifier#110]
The new 1.7.2 release is working great - many thanks!

One minor problem though is it does not support cached hash codes fields which have protected, or package-local access. The patch I submitted for this feature before did support that, so something might have gotten lost in the merge. It would be great if it allowed any access modified except public, for example.

**Comment by jqno** [comment]
I've just released version 1.7.3, which fixes this.
