### ISSUE TITLE
Validate that equals is false for null.

### ISSUE THREAD

**Issue by mmacfadden** [jqno/equalsverifier#112]
When doing code coverage, it looks like EqualsVerifier is not constructing and object and then passing in null.

My classes typically look like this:

```
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }

    if (obj == null) {
        return false;
    }

    if (getClass() != obj.getClass()) {
        return false;
    }

    MyObj other = (MyObj) obj;

    return new EqualsBuilder()
            .appendSuper(super.equals(obj))
            .append(this.field, other.field)
            .isEquals();
}
```

It seems that the obj == null check as well as the getClass() != obj.getClass() do not get exercised for branch coverage.  I am calling the verifier as such:

EqualsVerifier.forClass(MyObj.class)
        .usingGetClass()
        .verify();

Any thoughts?

P.S. Thanks for this great utility.

**Comment by jqno** [comment]
Hi Michael,

Thanks for reporting this!

However, it does surprise me, to be honest. EqualsVerifier has a suite of coverage tests where the build will fail if instruction coverage drops below 100%. One of the tests in this suite includes an equals method that looks identical to yours. I just changed it from instruction coverage to branch coverage and ran the test suite again, just to be sure, and it reports 100% coverage.

Also, there is a NonNullityTest that covers the whole range of cases when null is passed into an equals method. What would happen if you change `return false;` to `return true;` after the null check in your equals method?

Also, can you tell me more about your situation? Which version of EqualsVerifier are you using? (Coverage guarantees were introduced in version 1.4.) Maybe you could give me a full class that reproduces this behavior?

Cheers,
Jan

**Comment by mmacfadden** [comment]
Thanks for the reply.  I somehow didn't get notified.  I just came back to check.  I will get you the example I am seeing.

**Comment by jqno** [comment]
Hi Michael, I was going through the issues and noticed this is one was still open. Do you have some sample code for me? Otherwise, I'll probably close this issue later.

**Comment by jqno** [comment]
I'm closing this issue now, but please feel free to re-open it if you have the example!

**Comment by mmacfadden** [comment]
I actually just dug back in to this.  I have figured out the issue, which of course is not with your code!  What was happening, was I was trying to test an abstract class.  The abstract class needed to be subclassed to check the equals method.  The subclass actually had it's own check for null, therefore the super class never got a chance to cover those branches.  Sorry for wasting your time, but I suppose this could be a good FAQ item.

**Comment by jqno** [comment]
No problem, and thanks for getting back to me.
Is there a reason why you can't just pass the abstract class to EqualsVerifier?
