### ISSUE TITLE
Reflexivity AssertionError when tested class has a field whose hierarchy has an abstract class

### ISSUE THREAD

**Issue by alexkaratarakis** [jqno/equalsverifier#113]
Code demonstrating the issue:
https://gist.github.com/Danimoth/621ab0e819838e6b589f

Situation:
I have several value classes with a single field each (a double value). They all override equals() and hashCode(). They are all structured in the form*:
ParentClass (abstract class, which defines an abstract method value() ). 
ChildClass (with the actual implementation)

The ChildClass is not intented to be public, so the rest of the code only uses ParentClass as a type. 
A fully implemented example is given in the gist above. These classes pass all my tests, including the ones from EqualsVerifier. 

I then have a DerivedClass, that contains a single ParentClass field. This also implements equals() and hashCode. However, when trying to run EqualsVerifier on the DerivedClass, I get the message

> java.lang.AssertionError: Reflexivity: == used instead of .equals() on field: parentClass
> If this is intentional, consider suppressing Warning.REFERENCE_EQUALITY
> For more information, go to: http://www.jqno.nl/equalsverifier/errormessages"

This is pretty weird, because I am not using a reference equality, but the equals() method of the field. 
If I am not using the ParentClass-ChildClass hierarchy, but a final concrete class, then the issue does not occur. For example, if the ChildClass type is used as the field type in DerivedClass, then the test passes. 
- The reason why they have this form is that I am trying out AutoValue 1.1 (https://github.com/google/auto/tree/master/value). AutoValue usage dictates that I use an abstract class and generates some code. The equals() and hashCode() implementations are taken from the generated code.

**Comment by jqno** [comment]
Hi,

Sorry for the late reply.
Are you using version 1.7, by any chance? I've been able to reproduce your problem with these versions, but not with version 1.7.1 and 1.7.2. It looks like it's one of the things I fixed as a result of the issue raised in these comments:
- https://github.com/jqno/equalsverifier/issues/104#issuecomment-87377326
- https://github.com/jqno/equalsverifier/issues/104#issuecomment-87377330

Please let me know if updating the version helps!

Jan

**Comment by alexkaratarakis** [comment]
Hi Jan,
Indeed, latest version woks correctly!
Thanks :)

**Comment by jqno** [comment]
Glad to hear that! Thanks for the update :).
