### ISSUE TITLE
subclass error missing documentation

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#121]
This is missing documentation

```
java.lang.AssertionError: Subclass:
  Entity of type com.xenoterracide.AbstractEntityBase$$EnhancerByCGLIB$$8d2bf41f with id: 00000000-0000-0000-ffff-ffffffffffff
equals subclass instance
  Entity of type com.xenoterracide.AbstractEntityBaseTest$TestEntity with id: 00000000-0000-0000-ffff-ffffffffffff
```

superclass

```
package com.xenoterracide;


import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.domain.Persistable;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import java.util.UUID;

@MappedSuperclass
public abstract class AbstractEntityBase implements Persistable<UUID> {
    public static final String ID = "id";
    private static final String UUID2 = "uuid2";
    private static final long serialVersionUID = 8974616254520097505L;

    @Id
    @Access( AccessType.PROPERTY )
    @GeneratedValue( generator = UUID2 )
    @GenericGenerator( name = UUID2, strategy = UUID2 )
    private UUID id;

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public boolean equals( final Object o ) {
        if ( this == o ) {
            return true;
        }
        if ( null == o ) {
            return false;
        }
        if ( o instanceof AbstractEntityBase ) {
            AbstractEntityBase that = (AbstractEntityBase) o;

            if ( this.getId() != null && that.getId() != null ) {
                if ( this.getId().equals( that.getId() )) {
                    return true;
                }
            }
        }

        return false;
    }

    @Override
    public String toString() {
        return String.format( "Entity of type %s with id: %s", this.getClass().getName(), this.getId() );
    }

    @Override
    @Column( name = ID, columnDefinition = "uuid" )
    public UUID getId() {
        return this.id;
    }

    @SuppressWarnings( "unused" ) // jpa
    public void setId( final UUID id ) {
        this.id = id;
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }
}
```

Test class

```
package com.xenoterracide;

import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.Test;

public class AbstractEntityBaseTest {

    @Test
    public void testEquals() throws Exception {
        EqualsVerifier.forClass( AbstractEntityBase.class )
                .withRedefinedSubclass( TestEntity.class )
                .verify();
    }

    private static class TestEntity extends AbstractEntityBase {
    }
}
```

using `v1.7.3`

this is a corrected passing `equals` the `getClass` line appears to be what resolves the subclass issue.

```
    @Override
    public boolean equals( final Object o ) {
        if ( this == o ) {
            return true;
        }
        if ( null != o && o instanceof AbstractEntityBase ) {
            AbstractEntityBase that = (AbstractEntityBase) o;

            if ( this.getId() != null ) {
                if ( this.getId().equals( that.getId() )
                        && ( this.getClass() == that.getClass()
                        || this.getClass().isAssignableFrom( that.getClass() )
                ) ) {
                        return true;
                }
            }
            else if ( that.getId() == null ) { // this.id must already be null
                return true;
            }
        }

        return false;
    }
```

**Comment by jqno** [comment]
Thanks for the heads up, I'll add an entry to the website next weekend or so.

In the mean time, "withRedefinedSubclass" is only needed if you actually redefine equals in the subclass. If you don't intend to override equals in any of AbstractEntityBase's subclasses, you can mark the equals and hashCode methods final, and remove the "withRedefinedSubclass" line. If you do intent to override equals, then you should also do so in the TestEntity.
If neither of these will work in your situation, and you don't mind if equals isn't 100% correct, you can suppres Warning.STRICT_INHERITANCE. If you do want equals to be correct, I recommend reading this: http://www.artima.com/lejava/articles/equality.html

**Comment by xenoterracide** [comment]
I did read that article, especially looking for what was causing this error.

Thanks for the tip on STRICT_INHERITANCE, maybe the equals cannot be final warning could suggest it. I don't like marking classes or methods final because [I believe[(http://www.xenoterracide.com/2014/06/java-privacy-broken-by-design.html) that violates the [Open Closed Principle](https://en.wikipedia.org/wiki/Open/closed_principle). Worth saying that dealing with inheritance as the Article suggests, etc, suggests, is because otherwise equals violates Liskov Substitution.

I did have one other problem, that I'm unsure how to proceed on, if both id's are null the test has coerced me into returning true, yet this is the area where I might want to deal with it in a subclass that has more fields... entities have the unique problem of "if they have the identifier, they should be equal, as they are the same entity" but what if they haven't been assigned an id yet (handwringing over the fact that every framework has decided on database autoincrementing id's).

**Comment by jqno** [comment]
Hi Caleb,

That's a very good point on the Open-Closed Principle. Looking exclusively at equals, though, if you want it to be extensible, you have to design for that, otherwise you risk violating not just Liskov Substitution, but also symmetry and transitivity (from the equals contract). These issues aren't isolated to the offending subclass, either: these problems work their way all the way up to the inheritance chain. For instance, you can't really trust a Set<AbstractEntityBase> if you put a subclass instance into it with an incorrectly extended equals method.

There are only two ways to have extensibility (Open-Closed) and correctness (symmetry and transitivity): by doing the "canEqual" thing (and using EV's withRedefinedSubclass), or by not marking equals final but agreeing among your team not to actually extend it either (and using STRICT_INHERITANCE). I have my personal opinions about this, and I try to design EV's API such that it nudges users into the direction I prefer, but ultimately it's a judgment call which can be expressed in EqualsVerifier.

Regarding your second problem, you can take a look at Warning.IDENTICAL_COPY_FOR_VERSIONED_ENTITY. I got a green test with your AbstractEntityBase class by calling EV like this:

```
EqualsVerifier.forClass( AbstractEntityBase.class )
    .suppress(Warning.STRICT_INHERITANCE, Warning.IDENTICAL_COPY_FOR_VERSIONED_ENTITY, Warning.NONFINAL_FIELDS)
    .verify();
```

**Comment by jqno** [comment]
I've added an explanation to the website: http://www.jqno.nl/equalsverifier/2015/08/16/subclass-equals-subclass-instance/
