### ISSUE TITLE
Include @Embeddable as JPA exclusion for mutable fields

### ISSUE THREAD

**Issue by firemanphil** [jqno/equalsverifier#124]
When @Entity is specified, equals verifier excludes classes from the field-mutable check. @Embeddable should also be included in this exclusion as it also used to annotate JPA pseudo-entities.

**Comment by jqno** [comment]
Good point! I'll add that to the next release.

**Comment by jqno** [comment]
I just released version 1.7.5, which adds this feature. (Also for @MappedSuperclass.)

**Comment by firemanphil** [comment]
Thanks!
