### ISSUE TITLE
Help needed with error message: Significant fields: equals does not use map, or it is stateless

### ISSUE THREAD

**Issue by gerazenobi** [jqno/equalsverifier#140]
Hi Jan.

Was using your lib on JPA entities. I have the following error message thrown for one of them:

> "java.lang.AssertionError: Significant fields: equals does not use map, or it is stateless."

``` java
@Entity
@Table(name = "model_categorical_formats")
@IdClass(ModelCategoricalFormatId.class)
public class ModelCategoricalFormat {
    private Integer mapId;
    private Integer modelId;
    private Double singleBoundary;
    private String categoryDescription;
    private Map map;

    @Id
    @Column(name = "map_id")
    public Integer getMapId() {
        return mapId;
    }

    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    @Id
    @Column(name = "model_id")
    public Integer getModelId() {
        return modelId;
    }

    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    @Id
    @Column(name = "single_boundary")
    public Double getSingleBoundary() {
        return singleBoundary;
    }

    public void setSingleBoundary(Double singleBoundary) {
        this.singleBoundary = singleBoundary;
    }

    @Basic
    @Column(name = "category_description")
    public String getCategoryDescription() {
        return categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    @ManyToOne
    @JoinColumns({@JoinColumn(name = "map_id", referencedColumnName = "map_id", nullable = false, insertable = false, updatable = false),
            @JoinColumn(name = "model_id", referencedColumnName = "model_id", nullable = false, insertable = false, updatable = false)})
    public Map getMap() {
        return map;
    }

    public void setMap(Map map) {
        this.map = map;
    }

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !(o instanceof ModelCategoricalFormat)) return false;

        ModelCategoricalFormat that = (ModelCategoricalFormat) o;

        if (mapId != null ? !mapId.equals(that.mapId) : that.mapId != null) return false;
        if (modelId != null ? !modelId.equals(that.modelId) : that.modelId != null) return false;
        if (singleBoundary != null ? !singleBoundary.equals(that.singleBoundary) : that.singleBoundary != null)
            return false;
        if (categoryDescription != null ? !categoryDescription.equals(that.categoryDescription) : that.categoryDescription != null)
            return false;

        return true;
    }

    @Override
    public final int hashCode() {
        int result = mapId != null ? mapId.hashCode() : 0;
        result = 31 * result + (modelId != null ? modelId.hashCode() : 0);
        result = 31 * result + (singleBoundary != null ? singleBoundary.hashCode() : 0);
        result = 31 * result + (categoryDescription != null ? categoryDescription.hashCode() : 0);
        return result;
    }
}
```

I am assuming this error is due to the fact I am not using map field on my methods and if so, why would I need to?
Note that fields included on equals/hascode are the ones by default included by Intellij when generating the JPA entity for Hibernate. (hence assumed 'Map map' was not needed).

Thanks in advance your your help.

**Comment by jqno** [comment]
I'm assuming you're using version 2.0.x. In this version, EqualsVerifier assumes that all fields should be used in your equals method. You can ignore one or more of them with `withIgnoredFields`, or you can revert to the behavior of the 1.x versions by calling `.suppress(Warning.ALL_FIELDS_SHOULD_BE_USED)`.

Unfortuantely, I don't personally have a lot of experience using JPA. Am I correct to assume, based on your example, that in JPA entities, only field whose getter is marked with `@Column` participate in the equals contract? (That would explain why `map` doesn't count.)

At this point, EqualsVerifier looks at the `@Entity` annotation (to disable the immutability checks), but it doesn't look at the `@Column` annotation. If it indeed works like I described, then that would be a nice addition for a future version.

**Comment by gerazenobi** [comment]
Thanks for your response Jan.

I managed to make it worked with your suggestion. Strange enough I still had to specify prefab values for this field that I was going to ignore anyways as I would get:

> java.lang.AssertionError: Recursive datastructure.

Here is how the test ended up:

``` java
    @Test
    public void itShouldValidateEqualsContract() throws Exception {
        EqualsVerifier.forClass(ModelCategoricalFormat.class)
                .withPrefabValues(Map.class, new Map(1, 1, "", ""), new Map(1, 2, "", ""))
                .withIgnoredFields("map")
                .suppress(Warning.NONFINAL_FIELDS).verify();
    }
```

Regarding JPA entities I am in the same situation as you are, hence why I was following the suggestion of the auto generated entity; should I have any more knowledge about it I ll flick you an email.

Thanks !

**Comment by jqno** [comment]
Hi,

I'm glad you got it working. I agree it's a bit strange to have to give a prefab value for a field that isn't used in equals, but it's needed because EqualsVerifier has to verify that it's really not used (among a few other checks it does as well).

I'll close this issue now.
