### ISSUE TITLE
[Request] - Create "equals verifier" for "compare"

### ISSUE THREAD

**Issue by jaredsburrows** [jqno/equalsverifier#141]
Thank you so much for writing this EqualsVerifier library, could you add support for `compare` and `hashcode`, such as:

```
EqualsVerifier.forClass(Tuple.class).verify()
CompareVerifier.forClass(SpecialString.class).verify()
```

**Comment by jqno** [comment]
EqualsVerifier already checks `hashCode`.

From the example you give, I'm going to assume you want a check for `Comparable`, which has `compareTo` method, and not `Comparator`, which has the `compare` method you mention. Support for `Comparable` is a duplicate of #129.

**Comment by jaredsburrows** [comment]
@jqno Yes thanks.
