### ISSUE TITLE
Support for array invariants

### ISSUE THREAD

**Issue by jqno** [jqno/equalsverifier#143]
EqualsVerifier fails when equals asserts on a class invariant on the length of its array field.

See the discussion at https://groups.google.com/forum/#!topic/equalsverifier/lUJQZFQdU0w

**Comment by jqno** [comment]
I've just released version 2.1, which fixes this.

**Comment by ssoloff** [comment]
I verified EV 2.1 works as expected with the example I used as the basis for my post to the mailing list.  Thanks for the fix, Jan!
