### ISSUE TITLE
objenesis INDEX.LIST should not be included in equalsverifier jar

### ISSUE THREAD

**Issue by jchomicki** [jqno/equalsverifier#144]
INDEX.LIST is meant as an optimization when loading a jar, as it points to relevant files for the jar thus circumventing a linear search. When creating a fat jar, this file should be left out for each extra included jar as it is meant to work for that jar alone.

Right now, the objenesis library included in equalsverifier is not having it's INDEX.LIST deleted before inclusion in the final fat jar. This is causing a FileNotFound Exception in URLClassPath$JarLoader.getJarFile because it is trying to use the INDEX.LIST to find objenesis-2.1.jar when it does not exist in this case.

I'm using 1.7.5 and I checked up to 2.0.2

**Comment by jqno** [comment]
Thanks for reporting this, I wasn't aware of it. I'll see if I can configure my build such that this file is excluded from the uber jar.

In the mean time, I can't reproduce the FileNotFoundException you mention. What steps do I take to reproduce it?

**Comment by jqno** [comment]
I've just released version 2.1, which no longer contains the Objenesis stuff in the META-INF folder. Can you check if it works for you now?

**Comment by jchomicki** [comment]
The 2.1 release works for me, thanks!
I hit this during Bootstrap initialization using Dropwizard when starting my application with equalsverifier referenced.

**Comment by jqno** [comment]
Ah, so you mean that EqualsVerifier was on the classpath in production scope? That may be why it's never come up before, normally EV is only available in the test scope. I'm glad the new version solves your problem though!
