### ISSUE TITLE
Tests pass when I forgot super.equals()

### ISSUE THREAD

**Issue by UltraNurd** [jqno/equalsverifier#156]
# What steps will reproduce the problem?
1. Implement class hierarchy: AbstractParent -> AbstractChild -> ConcreteGrandchild
2. Override equals() in each but only check immediate member fields and forget to call super.equals()
3. EqualsVerifier.forClass(ConcreteGrandchild.class).withRedefinedSuperclass().verify() passes

(I added withRedefinedSuperclass() because of Symmetry AssertionError.)
# What did you expect?

I expected this test to fail, indicating that my equals() wasn't calling super.equals(), by checking case where child fields were all equal but one or more parent fields was not.
# Which version of EqualsVerifier are you using?

1.5.1

**Comment by jqno** [comment]
Thanks for reporting this. I'm on vacation at the moment, I'll take a look
when I get back.

**Comment by jqno** [comment]
Sorry for making you wait.

I've been trying to reproduce your issue, but I'm unable to. I set up a test project as you specified; you can look at it here: https://github.com/jqno/equalsverifier-issuerepro/tree/issue-156. (Make sure you're on branch `issue-156`.)

However, I'm getting a "Redefined superclass" error, as expected.

Can you modify the project in such a way that it reproduces your issue? Either by making a PR for the test project, or by telling me what to change. Without that information, I don't think I'll be able to help you.

**Comment by UltraNurd** [comment]
Sorry I missed this update... I'll take a look after the long weekend and try to replicate.

**Comment by jqno** [comment]
Are you still experiencing this problem? If not, I'll probably close this issue in a few days. (You can always reopen it, if you want)

**Comment by jqno** [comment]
Cleaning up...please re-open if you want to get back to this one.
