### ISSUE TITLE
Add Quick "how to do it right" docs

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#158]
so I know there's the long linked tutorial, but, it'd be nice to have some quick sample docs on the website. Specifically including ones for mutable jpa entity (with id), that has a superclass. How to write the equals, and then how to test with equals verifier). Apparently I forget while not having to do this (also our equals implementation is terribly broken).

**Comment by jqno** [comment]
You're right, I've been planning to add this for a while, just never got around to it. I'll bump it up on my priority list 🙂

**Comment by jqno** [comment]
If you like, you can add something yourself as well. I recently migrated the website to Github pages, it's in the gh-pages branch in this repo.

**Comment by jqno** [comment]
I wrote a lot of documentation in the past few weeks. It came out more like a manual than a 'quick do it right' document, but I still think it contains the information that you wanted. Please take a look and tell me what you think! Also, if you feel there's a topic I missed, please let me know :).
