### ISSUE TITLE
Support: Symmetry stupid equals implementation

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#162]
# What steps will reproduce the problem?

# What is the code that triggers this problem?

```
public class IdentifiableWithNameImpl implements IdentifiableWithName
{
	private static final long serialVersionUID = -5988029695996041386L;
	private final long id;
	private final String name;

	public IdentifiableWithNameImpl( final long id, final String name )
	{
		this.id = id;
		this.name = Objects.requireNonNull( name );
	}

	public IdentifiableWithNameImpl( final IdentifiableWithName entity  ) {
		this( entity.getId(), entity.getName() );
	}

	@Override
	public Long getId()
	{
		return id;
	}

	@Override
	public String getName()
	{
		return name;
	}

	@Override
	public String toString()
	{
		return this.getClass().getSimpleName() + '{' +
			"id=" + id +
			", name='" + name + '\'' +
			'}';
	}

	@Override
	public final boolean equals( final Object o )
	{
		if ( this == o )
		{
			return true;
		}
		if ( o instanceof IdentifiableWithNameImpl )
		{
			IdentifiableWithNameImpl that = (IdentifiableWithNameImpl) o;
			return that.canEqual( this )
				&& Objects.equals( id, that.id ) && Objects.equals( name, that.name );
		}
		return false;
	}

	protected boolean canEqual( final Object other ) {
		return other instanceof IdentifiableWithNameImpl;
	}

	@Override
	public final int hashCode()
	{
		return Objects.hash( id, name );
	}
}
```
```
public class SiteUserOrganizationSelectProjection extends IdentifiableWithNameImpl
	implements HasOrganizationNodeType
{

	private static final long serialVersionUID = 7456984334636485756L;
	private final OrganizationNodeType nodeType;
	private final int userLimit;

	@Override
	protected boolean canEqual( final Object other )
	{
		return other instanceof SiteUserOrganizationSelectProjection;
	}

	public SiteUserOrganizationSelectProjection(
		final long id,
		final String name,
		final OrganizationNodeType nodeType,
		final int userLimit )
	{
		super( id, name );
		this.nodeType = Objects.requireNonNull( nodeType );
		this.userLimit = Objects.requireNonNull( userLimit );
	}

	@Override
	public OrganizationNodeType getOrganizationNodeType()
	{
		return nodeType;
	}

	public int getUserLimit()
	{
		return userLimit;
	}
}
```

```
public class SiteUserOrganizationSelectProjectionTest
{

	@Test
	public void testEquals() {
		EqualsVerifier.forClass( SiteUserOrganizationSelectProjection.class ).verify();
	}
}
```
Please try to provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

# What error message or stack trace does EqualsVerifier give?

```java.lang.AssertionError: Symmetry:
  SiteUserOrganizationSelectProjection{id=1, name='one'}
does not equal superclass instance
  IdentifiableWithNameImpl{id=1, name='one'}
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:367)
	at
com.my.SiteUserOrganizationSelectProjectionTest.testEquals(SiteUserOrganizationSelectProjectionTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)```

# What did you expect?

well I thought this implementation of equals is correct per example: http://www.artima.com/lejava/articles/equality.html, but I think I'm missing something obvious... sorry, been headdesking for about 30 minutes, I'm pretty sure it's my code and not an actual bug in equalsverifier. 

# Which version of EqualsVerifier are you using?

Tried `1.7.7`, `1.7.8` and `2.1.7`

# Please provide any additional information below.

**Comment by jqno** [comment]
Hi!

Since this isn't really an issue, it's better to post this on the Google Group next time: https://groups.google.com/forum/?fromgroups#!forum/equalsverifier 😄 

The problem is that you override `equals` in `SiteUserOrganizationSelectProjection`. The way the `canEquals` dance works, is that both parties do an instanceof check to see if they are mutually compatible, so to speak.

Also, when you do this, you need to call `.withRedefinedSuperclass()` on EqualsVerifier, so EqualsVerifier also knows it has to follow the little dance. (You shoud call `.withRedefinedSubclass()` on `IdentifiableWithNameImpl` if you intend to EqualsVerify that too.)

I suppose this would be a nice addition to the "how to do it right" docs that we were talking about in #158 😄

**Comment by xenoterracide** [comment]
> The problem is that you override equals in SiteUserOrganizationSelectProjection. The way the canEquals dance works, is that both parties do an instanceof check to see if they are mutually compatible, so to speak.

no I didn't, actually I think not overriding was the problem (because the outer interlock), I eventually got it... and then proceeded to delete it anyways... since I found a way to implement my solution without needing the extra fields in `SiteUserOrganizationSelectProjection` yay for legacy code... 

> Also, when you do this, you need to call .withRedefinedSuperclass() on EqualsVerifier, so EqualsVerifier also knows it has to follow the little dance. (You shoud call .withRedefinedSubclass() on IdentifiableWithNameImpl if you intend to EqualsVerify that too.)

yeah had also tried that, just probably not in what I'd pasted. also had a another test for `IdentifiableWithNameImpl` but it was passing...

> Since this isn't really an issue, it's better to post this on the Google Group next time: https://groups.google.com/forum/?fromgroups#!forum/equalsverifier 

I'll try to remember to do that next time.

> I suppose this would be a nice addition to the "how to do it right" docs that we were talking about in #158 😄

yeah, all the, how do I write this extending impl so that it's not super duplicative, or error prone over 150 classes  (400k lines of code) are appropriately final or not, do I do identity or what if I want identity as just the quick check... how do I deal with proxies. What if you want 2 objects that aren't the same type to be be compared... e.g. what's the recommended way to do that.

Thanks this  project is still awesome ;) even if somehow implementing equals always seems like there's some edge case hook, though the working version never seems that complicated

**Comment by jqno** [comment]
Haha, yes, I meant to say that you didn't override `equals` in `SiteUserOrganizationSelectProjection`, and then I said the opposite. I guess I need more sleep ;).

I'm glad you got it to work. And indeed, `equals` is full of little edge cases. I hope EqualsVerifier helps people to find them, and correct them where needed. Hopefully during the christmas break, I'll find some time to expand the documentation a little.
