### ISSUE TITLE
Security manager preventing EqualsVerifier to create dynamic subclass

### ISSUE THREAD

**Issue by sywor** [jqno/equalsverifier#163]
The steps are pretty well described [here](https://groups.google.com/forum/?fromgroups=#!topic/equalsverifier/9gU88P9Z6zQ).
If there is a abstract class in a signed jar that is extended in an other class the security manager throws an security exception when the equals verifier tries to create an dynamic subclass in the signed jar. 

### What error message or stack trace does EqualsVerifier give?
java.lang.SecurityException: class "...ExternalClass$$DynamicSubclass"'s signer information does not match signer information of other classes in the same package

### Which version of EqualsVerifier are you using?
2.1.8

### Please provide any additional information below.
I'm adding this issue here for bookkeeping. The issue could possibly be solved by using prefab values.

**Comment by jqno** [comment]
As I've asked in the thread you link to, you have to help me out here. Can you please give me such a jar, or show me how to make one, so I can reproduce this issue?
I really want to fix this issue, but I have no experience with signed jars and work is keeping me pretty busy, so if you help me out I can fix it much sooner than if I have to figure everything out myself...

**Comment by sywor** [comment]
Its been a while and my colleague finally had some spare time over to throw together a small project to demonstrate the bug. 
Link to project: [https://github.com/sywor/EqualsVerifierBug](https://github.com/sywor/EqualsVerifierBug) 
In the ExternalProject pom file it is important that you set the path the the .keystore file

**Comment by jqno** [comment]
Thank you, and also please thank your colleague for taking the time to do this 😄.
I was able to reproduce the issue with this repo. I will investigate further, and I'll get back to you when I know more.

**Comment by jqno** [comment]
I found a solution for this issue!
I have a couple of other things I want to do before I release, but they shouldn't take too much time. I'll let you know when it's released.

**Comment by jqno** [comment]
I've just released version 2.3, which should fix this problem.
