### ISSUE TITLE
Fix "Illegal reflective access" warnings on Java 9

### ISSUE THREAD

**Issue by jqno** [jqno/equalsverifier#172]
# What steps will reproduce the problem?

Compile EqualsVerifier on Java 9. I've tested this on version 9+181 but later versions will probably have the same warning.

# What error message or stack trace does EqualsVerifier give?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (file:/Users/jqno/workspaces/equalsverifier/equalsverifier/target/classes/) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

# What did you expect?

No warnings

# Which version of EqualsVerifier are you using?

2.3.2 or higher

# Please provide any additional information below.

Calling `setAccessible` on classes from other modules is frowned upon in Java 9, and probably deprecated in Java 10.

**Comment by jqno** [comment]
See also the discussion in #169.

**Comment by stefan-reich** [comment]
That is so bad (complaining about setAccessible). Java is going backwards with that. so useless to suddenly disallow basic behavior. I will have to make a workaround in my language.

**Comment by jqno** [comment]
Warnings are gone in version 2.4.1.

**Comment by don-vip** [comment]
Awesome!
