### ISSUE TITLE
print both objects when in error

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#175]
Basically it can be a pain in the behind to figure out why something isn't equals, when `EqualsVerifier` only prints one side of the equation.

# What steps will reproduce the problem?

    @Test
    public void equivalence() {
        EqualsVerifier.forClass( Classification.class )
                .withIgnoredFields( "sortWeight" )
                .withRedefinedSuperclass()
                .verify();
    }

doing something like this, where the other side of `getId() != null`

```
	protected boolean innerEquals( Object obj )
	{
		final Identifiable other = (Identifiable) obj;
		return !isNew() // < DRAGONS!!
			&& Objects.equals( this.getId(), other.getId() );
	}

	default boolean isNew() {
		return getId() == null;
	}
```
# What is the code that triggers this problem?

Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: Reflexivity: object does not equal an identical copy of itself:
  Classification{name='one'} AbstractPersistedEntity{id=null}
If this is intentional, consider suppressing Warning.IDENTICAL_COPY
```

# What did you expect?

obviously you need a `toString` that works like ours to get the format, but it would be useful if equalsverifier showed both objects, and which was passed to which.

```
java.lang.AssertionError: Reflexivity: object does not equal an identical copy of itself:
  this: Classification{name='one'} AbstractPersistedEntity{id=null}
  that: Classification{name='one'} AbstractPersistedEntity{id=2}
If this is intentional, consider suppressing Warning.IDENTICAL_COPY
```

# Which version of EqualsVerifier are you using?

test both
```
-                               <version>2.1.7</version>
+                               <version>2.3.3</version>
```

**Comment by jqno** [comment]
Can you give me a class (or two classes) that I can copy-paste into my IDE and compile? Basically it can be a pain in the behind to figure out what's going wrong, given that you have the problem right in front of you and I have to try and reproduce it in my spare time. ;)

**Comment by xenoterracide** [comment]
the problem is obviously that the `isNew` is not symmetric
```
public interface Identifiable extends Persistable<Long>
{

	@Override
	Long getId();

	@Override
	@Transient
	default boolean isNew() {
		return getId() == null;
	}
   }

 @Entity
    public class TC implements Identifiable {

        private static final long serialVersionUID = -784473498456734159L;
        private Long id;

        @Override
        public String toString() {
            return "TC{" +
                    "id=" + id +
                    '}';
        }

        @Override
        public final boolean equals( Object o ) {
            if ( this == o ) {
                return true;
            }
            if ( o instanceof TC) {
                TC tc = (TC) o;
                return tc.canEqual( this ) && !isNew() && Objects.equals( id, tc.id );
            }
            return false;
        }

        protected boolean canEqual( Object that ) {
            return that instanceof TC;
        }

        @Override
        public final int hashCode() {
            return Objects.hash( id );
        }

        @Override
        public Long getId() {
            return id;

        }

        public void setId( Long id ) {
            this.id = id;
        }
    }
```

probably a little more than what's actually needed to reproduce

```
        EqualsVerifier.forClass( TC.class ).verify();
```

**Comment by jqno** [comment]
Thanks for that, this makes it a lot easier for me :).

EqualsVerifier actually gives the correct response in this case. Apart from being asymmetric, TC's equals method is actually not reflexive either. That's easy to demonstrate with this failing test:

```java
    @Test
    public void testReflexivity() {
        TC a = new TC();
        a.setId(null);
        TC b = new TC();
        b.setId(null);
        assertEquals(a, b);
    }
```

JUnit gives the following error message:

```
java.lang.AssertionError: expected: nl.jqno.equalsverifier.TC<TC{id=null}> but was: nl.jqno.equalsverifier.TC<TC{id=null}>
Expected :nl.jqno.equalsverifier.TC<TC{id=null}> 
Actual   :nl.jqno.equalsverifier.TC<TC{id=null}>
```

EqualsVerifier does precisely the same thing when it produces the error message you mentioned. The reason why it only prints a single side of the equation, is because both sides are exactly the same, as you can also see from JUnit's error message.

**Comment by xenoterracide** [comment]
well, I won't pretend to say I understand each of the rules off the top of my head. Of course my real world code is anything but this simple. The code pasted is actually from 3 or 4 different java files. It's part of a recursive entity hierarchy that all have this same "id" pattern. These entities have probably 500 lines each. I'm just trying to save myself some debugging time, and I think in this case, it might have been 1 and 2 for the ids, but I'll double check. That may still be a reflexivity issue, I was just trying to get more info to be sure of what I was looking at to help me narrow it down, since it's testing in a loop.

**Comment by jqno** [comment]
Reflexivity is the simplest rule: it says an object should be equal to itself. Adding the other object to the error message will give you zero extra information, because it's exactly the same object.

There is exactly 1 exception to this rule, and that's when, like in your case, you have this "id" pattern and an id was not yet assigned to the object. For those cases, you can suppress `Warning.IDENTICAL_COPY` -- precisely like EqualsVerifier's error message already says.

I highly recommend that you track down a copy of Effective Java by Josh Bloch, and read its chapter about equals. It explains the rules quite clearly; they're not very hard to understand.
