### ISSUE TITLE
Release for Java 8

### ISSUE THREAD

**Issue by Blarne** [jqno/equalsverifier#181]
# What error message or stack trace does EqualsVerifier give?
No error. When importing to Java 8 project as maven library, unexpected libraries are imported.

# What did you expect?
No dependency to JodaTime, Guava, etc. Optimize code for JDK 8+ only.

# Which version of EqualsVerifier are you using?
2.4

# Please provide any additional information below.
Prepare release with no backward compatibility < Java 8 based on standard Java 8 functions and methods (ie Streams, LocalDateTime).

**Comment by jqno** [comment]
Dropping support for Java 7 is on my road map, but I have a few other things I need to get done before I can do that. JodaTime and Guava are needed for unit tests, so they're not going to go away.

I'm wondering though, what the problem is precisely? Why do you need this?

**Comment by Blarne** [comment]
Only for standardize of this nice library :) If you can, I will help you.

**Comment by jqno** [comment]
Thank you for the kind offer! However, there are unfortunately still projects on Java 7. If we move EqualsVerifier to Java 8, that means that they cannot use it anymore.

I do want to move EqualsVerifier to Java 8 at some point, but it will probably have wait until Java 10 is out, or at least until #172 is done.
