### ISSUE TITLE
Cannot get EV to work with directly self-referencing class

### ISSUE THREAD

**Issue by baron1405** [jqno/equalsverifier#187]
I have the situation of class Foo which contains a field of type Set<Foo>. As expected I get the Recursive Data Structure error. However, I cannot seem to prefab my way out of the problem. The example on the website assumes an intermediate value (i.e. Foo references Bar reference Foo). In my case, it is a direct self-reference so perhaps that is the problem. Any suggestions would be very appreciated.

**Comment by jqno** [comment]
If you have a directly self-referencing class like this:

```java
class Tree {
    private final Tree left;
    private final Tree right;

    // constructors and equals method etc
}
```

you can just add a prefab value for Tree itself when testing Tree. It feels a little strange but it does work.

However, you mention that you also have a Set. What does the self-reference look like in your case? Can you give me some code so I can understand your situation better?

**Comment by baron1405** [comment]
Turns out it was pilot error. I thought I was adding the prefab value but was not (have a wrapper class). The Set was not a problem. Your error message was clear, I was just not getting the prefab where in to the verifier.

**Comment by jqno** [comment]
OK, glad it's sorted out!
