### ISSUE TITLE
Performance. Test works too long

### ISSUE THREAD

**Issue by turbanoff** [jqno/equalsverifier#190]
# What steps will reproduce the problem?
I have unit test which check equality for one class.
This test run for a long time. I checked - it's due to repeating non-null checking for same type
![default](https://user-images.githubusercontent.com/741251/38835999-65321e58-41d5-11e8-8fc3-6b6dde579272.png)

AccountActionCriteria class has 34 fields.
I checked count of packageHasAnnotation calls from single test. Its 7158.

    7151. Check package for AccountActionCriteria has annotation JSR305_DEFAULT_ANNOTATION_NONNULL
    7152. Check package for AccountActionCriteria has annotation ECLIPSE_DEFAULT_ANNOTATION_NONNULL
    7153. Check package for AccountActionCriteria has annotation FINDBUGS1X_DEFAULT_ANNOTATION_NONNULL
    7154. Check package for AccountActionCriteria has annotation JSR305_DEFAULT_ANNOTATION_NONNULL
    7155. Check package for AccountActionCriteria has annotation ECLIPSE_DEFAULT_ANNOTATION_NONNULL
    7156. Check package for AccountActionCriteria has annotation FINDBUGS1X_DEFAULT_ANNOTATION_NONNULL
    7157. Check package for AccountActionCriteria has annotation JSR305_DEFAULT_ANNOTATION_NONNULL
    7158. Check package for AccountActionCriteria has annotation ECLIPSE_DEFAULT_ANNOTATION_NONNULL

# What did you expect?
Faster test execution time. Can annotation info be cached?

# Which version of EqualsVerifier are you using?
2.4.5

**Comment by jqno** [comment]
Thanks for reporting this. I knew that part of the code wasn't optimal, but I didn't know it was this bad. I'll look into it.
