### ISSUE TITLE
Running test briefly opens an AWT frame

### ISSUE THREAD

**Issue by ekoutanov** [jqno/equalsverifier#192]
# What steps will reproduce the problem?
Run any test from Eclipse 4.7.3a. You'll briefly notice an AWT frame open and close. The test code and the method under test has nothing to do with AWT/Swing.

# What is the code that triggers this problem?
Any test seems to trigger this.
Environment:
* oracle64-1.8.0.131
* MacOS 10.12.5
* Eclipse 4.7.3a

The bug appears to be related to this [commit](https://github.com/jqno/equalsverifier/commit/7c222b22cbfa365275dd774b36be6d89b80ca2f0)

The problem with `JavaApiPrefabValues.addAwtClasses()` is that it inadvertently bootstraps AWT, which wouldn't be a problem if the JVM is launched without a graphics environment, with `-Djava.awt.headless=false`. However, when running tests from an IDE, this is not an option. Seeing an AWT frame flash by is mildly irritating.

Suggest making the `addAwtClasses()` optional, or otherwise provide an option in the `EqualsVerifier` API to disable AWT prefab.

# What error message or stack trace does EqualsVerifier give?
No error message. Test completes successfully.

# What did you expect?
Test should run without invoking AWT.

# Which version of EqualsVerifier are you using?
2.4.2 (version 2.4.1 works fine)

**Comment by jqno** [comment]
Thanks for reporting this. Around that time I was upgrading my build script for Java 9, so I figured it had something to do with that, but you're right, if I remove the AWT classes, the popup goes away.

Incidentally, it only occurs on Java 8 (and, presumably, 7). In Java 9 it doesn't appear either way.

I lean towards your first suggestion of making `addAwtClasses()` optional, but it's also more work and I'm currently working on another feature, so it might take a while before I get to this. You say this issue is 'mildly irritating', so I'm assuming that's ok. If not, let me know and I can add something quick 'n dirty instead.

**Comment by ekoutanov** [comment]
The 'mildly irritating' element is when you're working on MacOS with your IDE in full-screen mode. When an AWT frame shows up, it forces the windowing system to switch desktops (because it can't render the new frame in the same desktop as your full-screen IDE) and, worse still, when it switches to a different desktop it won't switch back automatically. So yeah, maybe upgrade the _mildly_ rating to _moderately_. 😃 
 
In terms of priority, this isn't too big a deal at the moment; I've just downgraded to 2.4.1 for now until I switch my projects to Java 10.

The AWT issue aside, and although I don't profess to understand the codebase (limited to my brief look at the commits), another suggestion might be to 'lazily' prefab values based on what the unit test is actually trying to do. I appreciate this is more work, but there is one clear benefit — lazy prefab avoids unnecessarily invoking static initializers of classes that are being prefabbed, since in 99.9% of cases these classes won't actually get used. This should speed up the EqualsVerifier initialisation times, reduce the number of tenured objects and avoid any future (unknown) problems that are in a similar league to this one.

**Comment by jqno** [comment]
You have a good point about making the prefab values lazy. I've been refactoring those lately anyway, so I'll take that into account as well.

In the mean time, I'll see if I can make a quick fix for just the AWT classes.

**Comment by jqno** [comment]
I just released a fix (version 2.4.6), let me know if it fixes the problem for you!

**Comment by ekoutanov** [comment]
Fixed confirmed. Thanks!
