### ISSUE TITLE
Transient field is not ignored

### ISSUE THREAD

**Issue by mark-grunn** [jqno/equalsverifier#196]
# What steps will reproduce the problem?
Attempting to verify a class with a transient field using lombok's @EqualsAndHashCode does not seem to run the transient fields with "withIgnoredFields"

# What is the code that triggers this problem?
Model.java
```
@Entity
@EqualsAndHashCode
public final class Model {

    @Transient
    @EqualsAndHashCode.Exclude
    private Boolean condition;

    private String test;
}
```

EqualsVerifierTest.java
```
    @Test
    public void equalsVerifierTest() {
        EqualsVerifier<?> verifier = EqualsVerifier.forClass(pojoClass.getClazz());

        // Below code required to not fail
//        if (pojoClass.getClazz().equals(Model.class)) {
//            verifier.withIgnoredFields("condition"); // Reason: transient field
//        }
        verifier.verify();
    }
```

# What error message or stack trace does EqualsVerifier give?
```
java.lang.AssertionError: Significant fields: equals does not use condition, or it is stateless.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:375)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:361)
	at com.example.equalsverifier.EqualsverifierApplicationTests.equalsVerifierTest(EqualsVerifierTest.java:32)
```

# What did you expect?
As noted in http://jqno.nl/equalsverifier/manual/jpa-entities/ under "Transient Fields" I would expect the transient field "condition" to be called with "withIgnoredFields".

# Which version of EqualsVerifier are you using?
2.4.6

**Comment by jqno** [comment]
Indeed, I was able to reproduce this issue (both with and without Lombok). I'll fix this in the next version, which I hope to release in the next few days.

**Comment by srenkens** [comment]
That would be nice Jan, our team will be happy 😉
Thanks for the excellent tool

**Comment by jqno** [comment]
I just released a fix!

**Comment by hohwille** [comment]
For the record: I faced this bug in latest version (`3.10.1`) so it is IMHO not (properly) fixed.
Maybe in my case the problem might be related to the fact that the transient filed is located in a super-class that other beans inherit that are tested via equals-verifier. The only solution I could find so far is to completely disable the static check (`suppress(Warning.TRANSIENT_FIELDS)`).

**Comment by jqno** [comment]
Hi!
Could you please post the code that triggers this behaviour for you? I do have some tests that test the case when the `@Transient` annotation is present in a superclass, but maybe I'm missing something. Unfortunately, I can't figure out what exactly, from your description.
