### ISSUE TITLE
Does not work with class having j.n.ByteBuffers

### ISSUE THREAD

**Issue by dmitry-timofeev** [jqno/equalsverifier#198]
# What steps will reproduce the problem?
Run EqualsVerifier.verify on any class that has a field of type `j.n.ByteBuffer`, and you'll receive the following error: `Significant fields: equals does not use <field name of type ByteBuffer>, or it is stateless.`.

# What is the code that triggers this problem?
The first test is the one that triggers the problem, the second — a workaround, the last — a baseline.
```java
import java.nio.ByteBuffer;
import java.util.Objects;
import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.Test;

public class EqualsVerifierDoesNotWorkWithByteBufferTest {

  @Test
  public void value1WithByteBuffer() {
    EqualsVerifier.forClass(Value1ByteBuffer.class)
        .verify();
  }

  @Test
  public void value1WithByteBufferAndPrefab() {
    EqualsVerifier.forClass(Value1ByteBuffer.class)
        .withPrefabValues(ByteBuffer.class,
            ByteBuffer.wrap(new byte[] {0}),
            ByteBuffer.wrap(new byte[] {1}))
        .verify();
  }

  @Test
  public void value2NoByteBuffer() {
    EqualsVerifier.forClass(Value2String.class)
        .verify();
  }
}

final class Value1ByteBuffer {
  private final ByteBuffer body;

  Value1ByteBuffer(ByteBuffer buf) {
    this.body = buf;
  }

  @Override
  public boolean equals(Object obj) {
    if (!(obj instanceof Value1ByteBuffer)) {
      return false;
    }
    Value1ByteBuffer other = (Value1ByteBuffer) obj;
    return Objects.equals(body, other.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body);
  }
}


final class Value2String {
  private final String body;

  Value2String(String body) {
    this.body = body;
  }

  @Override
  public boolean equals(Object obj) {
    if (!(obj instanceof Value2String)) {
      return false;
    }
    Value2String other = (Value2String) obj;
    return Objects.equals(body, other.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body);
  }
}
```

# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: Significant fields: equals does not use body, or it is stateless.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:375)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:361)
	at EqualsVerifierDoesNotWorkWithByteBufferTest.value1WithByteBuffer(EqualsVerifierDoesNotWorkWithByteBufferTest.java:29)
```

# What did you expect?
Ideally, to work out of the box with no need to provide "prefab values". If that is not possible or does not make sense to implement in the library, provide an error message that explains that the user _must_ provide these values. The current error message suggest a problem in `equals/hashCode` (i.e., missing comparison operation of some field), not in the test code, which is not true.

# Which version of EqualsVerifier are you using?
2.4.7

**Comment by jqno** [comment]
Thanks for reporting this.

I've reproduced the issue, and it's also true for other Buffers such as CharBuffer. I'll add them to the built-in prefab values.

Unfortunately I might not be able to do that before I leave on holiday. I'll let you know when I release a fix. In the mean time you can manually add the prefab values as a workaround.

**Comment by jqno** [comment]
Also, thank you for the elaborate code samples. Unfortunately, not everybody does this, but it makes reproducing these kinds of issues so much easier. Thank you!

**Comment by dmitry-timofeev** [comment]
Thank you very much for taking a look at the issue!

**Comment by jqno** [comment]
Managed to squeeze in a release today. Check out version 2.4.8!

**Comment by dmitry-timofeev** [comment]
Brilliant, thank you! 

Just wondering — is the fact that EV did not show a proper error message in this case a separate bug? I am not sure, but I think I saw once a message asking for "prefab values" for my own data type.

**Comment by jqno** [comment]
I have to admit I didn't really look into it. I agree though, it should have shown a proper error message instead of this one.
