### ISSUE TITLE
update to Checkstyle 8.14 and make maven property for it

### ISSUE THREAD

**Issue by romani** [jqno/equalsverifier#216]
based conversation at https://github.com/checkstyle/checkstyle/issues/5510#issuecomment-432135191

please update Checkstyle version to most recent and make a property for checkstyle version to let Checkstyle project simply clone your repo, and run validation with specifying SANPSHOT version.

Example of how qualsverifier be used in Checkstyle ci - https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L75

**Comment by jqno** [comment]
Done!
