### ISSUE TITLE
Java 9+ Illegal reflective access on java.time.OffsetDateTime

### ISSUE THREAD

**Issue by eggilbert** [jqno/equalsverifier#217]
I stumbled across another instance of https://github.com/jqno/equalsverifier/issues/214 and friends for `java.time.OffsetDateTime` 😿 

It looks like most of the `java.time` package has prefab values already (like `LocalDateTime` and `ZonedDateTime`), but not the `OffsetXYZ` variants. Can these be added?

Apologies for creating another issue here. I was running things with `--illegal-access=warn` before reporting #214 to try and include everything at once, but either I wasn't using `java.time.OffsetDateTime` yet at the time or somehow missed it in the output. I was surprised when there were still warnings after pulling in the new 3.0.1 release.

# What steps will reproduce the problem?

Use EqualsVerifier on a class containing `java.time.OffsetDateTime`.

# What is the code that triggers this problem?

```java
package my.company;

import nl.jqno.equalsverifier.EqualsVerifier;
import nl.jqno.equalsverifier.Warning;
import org.junit.jupiter.api.Test;

import java.time.OffsetDateTime;
import java.util.Objects;

class OffsetDateTimeTest {
    static class POJO {
        private OffsetDateTime field;

        public OffsetDateTime getField() {
            return field;
        }

        public void setField(OffsetDateTime field) {
            this.field = field;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            POJO pojo = (POJO) o;
            return Objects.equals(field, pojo.field);
        }

        @Override
        public int hashCode() {
            return Objects.hash(field);
        }
    }

    @Test
    void equalsContract() {
        EqualsVerifier.forClass(POJO.class)
            .usingGetClass()
            .suppress(Warning.NONFINAL_FIELDS)
            .verify();
    }
}
```

# What error message or stack trace does EqualsVerifier give?

```
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (...) to field java.time.OffsetDateTime.dateTime
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (...) to field java.time.OffsetDateTime.offset
```

# What did you expect?

No compiler warnings emitted

# Which version of EqualsVerifier are you using?

3.0.1

# Please provide any additional information below.

Running on OpenJDK 11

**Comment by jqno** [comment]
Thanks for letting me know about this! I don't mind the extra issue.

However, I still have a lot of things going on so I might not get to it super quickly. (PRs are always welcome though 😉)

**Comment by jqno** [comment]
Thanks for the PR! I'll try to squeeze in a release in the next few days.

**Comment by eggilbert** [comment]
Thanks, that would be great :+1:

**Comment by jqno** [comment]
Released! 🎉
