### ISSUE TITLE
put GAV on website

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#219]
although I'm hoping for a gradle feature to straighten this out... I can never remember the group for equalsverifier.

putting the GAV (group:artifact:version) on the front page of the site would help

https://jqno.nl/equalsverifier/

I'd be ok with just (this is modern gradle, should work for both groovy and kotlin dsl's)

```
    testImplementation("nl.jqno.equalsverifier:equalsverifier:3.+")
```

**Comment by jqno** [comment]
The coordinates are already on the website (under Getting Started) and in the README on Github. They are in Maven syntax though, but the information is the same. Is that too confusing? (Not trying to be a smartass here, I'm genuinely asking. I haven't used Gradle a lot.)

**Comment by xenoterracide** [comment]
The syntax isn't confusing, I can translate it, but I'll be honest, looking here https://jqno.nl/equalsverifier/ I didn't even see getting started, and I looked in the manual, didn't see it there either. I did see it on the README, but seems like something that should be more obvious/on the front page. note: GAV is actually a maven term, it's the same thing different syntax in the xml. I'd be fine with a maven block on the front page, though some people are now doing a tab-ish thing that allows you to switch between gradle/maven for how to define. That's really only useful for copy/paste which I appreciate, but still.

**Comment by jqno** [comment]
Ah, so then I misunderstood your question. I thought you wanted the Gradle syntax added to the Maven syntax, but what you were really asking for was to move things to the frontpage. That's probably a good idea, so I'll do that.

(The "Getting Started" page is part of the manual BTW, so it was in the manual after all 😉)

**Comment by jqno** [comment]
Done!
