### ISSUE TITLE
Empty Enum will make problem again

### ISSUE THREAD

**Issue by unikzforce** [jqno/equalsverifier#242]
# What steps will reproduce the problem?
Just like the [Issue](https://github.com/jqno/equalsverifier/issues/199), again empty enums are making trouble.
# What is the code that triggers this problem?

Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!

# What error message or stack trace does EqualsVerifier give?

# What did you expect?

# Which version of EqualsVerifier are you using?

# Please provide any additional information below.

**Comment by jqno** [comment]
I've run the failing test from issue #199 against the current master of EqualsVerifier (version 3.1.9) and it passes. Can you please be more specific, and fill out the complete issue template?

**Comment by unikzforce** [comment]
of course i'll edit the issue ASAP.

**Comment by unikzforce** [comment]
I'll close this issue for now.  but if i could reproduce the problem i'll try to reopen.
