### ISSUE TITLE
An illegal reflective access operation warning in 3.1.12

### ISSUE THREAD

**Issue by igouss** [jqno/equalsverifier#285]
Similar to https://github.com/jqno/equalsverifier/issues/248
According to the ticket it was supposed to be resolved in 3.1.10

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (file:/home/igoussev/.gradle/caches/modules-2/files-2.1/nl.jqno.equalsverifier/equalsverifier/3.1.12/83cde27c2cfffbad1500a19707d38f47c00947e5/equalsverifier-3.1.12.jar) to field java.lang.Thread.name
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by jqno** [comment]
In #248, it was resolved for the case where the class you're testing with EqualsVerifier has fields of type `java.lang.reflect.Method` (or of any other type in the `java.lang.reflect.*` package). Unfortunately, this error must be addressed for all types individually.

What type does your class have that triggers this error? If you're not sure, you can post the code of your class here. I can't help you without this information.

**Comment by igouss** [comment]
```
import nl.jqno.equalsverifier.EqualsVerifier;
import nl.jqno.equalsverifier.Warning;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;

import static org.mockito.Mockito.mock;

@RunWith(MockitoJUnitRunner.class)
public class ConnectionInfoTest {
    @Test
    public void equalAndHashCodeTest() {
        EqualsVerifier.forClass(ReplicationConnection.class)
                .withPrefabValues(Thread.class, mock(Thread.class), mock(Thread.class))
                .withOnlyTheseFields("stream")
                .suppress(Warning.STRICT_INHERITANCE)
                .verify();
    }
}
```


````
@Slf4j
@EqualsAndHashCode(of = "stream")
public class ReplicationConnection implements HealthIndicator {
    private final Thread replicationConnectionThread;

    @Getter
    private final ReplicationStream stream;
.....
```

**Comment by jqno** [comment]
The error message seems to indicate that the issue is in the `Thread` class, but EqualsVerifier already knows about Thread and provides a built-in prefab value. There's a unit test for that which runs on JDK 9, 10, 11, 12, 13 and 14 on every commit. So this should not be happening.

I notice you provide your own prefab values for `Thread` as well. Why do you do this? Also, could the issue be caused by the fact that you give it `mock(Thread.class)` instead of a "real" value? What happens when you remove the `.withPrefabValues` line, or when you replace the mocks by actual instances of the `Thread` class?

**Comment by igouss** [comment]
I'm not sure why we pre-fab values, this test was added 2 years ago. We probably used old version of the equalsverifier that needed this.
```        
    @Test
    public void equalAndHashCodeTest() {
        Thread redThread = new Thread("red");
        Thread greenThread = new Thread("green");

        EqualsVerifier.forClass(ReplicationConnection.class)
                .withPrefabValues(Thread.class, redThread, greenThread)
                .withOnlyTheseFields("stream")
                .suppress(Warning.STRICT_INHERITANCE)
                .verify();
    }
````
Gives the same error. When I remove `withPrefabValues` test passes without an error.

**Comment by jqno** [comment]
Strange, I cannot reproduce the problem. But it would seem that we've found a solution anyway :).
