### ISSUE TITLE
IlleagalStateException Precondition: both values are equal

### ISSUE THREAD

**Issue by cptully** [jqno/equalsverifier#337]
# What steps will reproduce the problem?
I am currently working on adding unit tests to an existing project with none. I stumbled across this project as I was pondering writing unit tests for my equals method. At the same time I ran across the Apache Commons EqualsBuilder and HashCodeBuilder.

I have implemented the EqualsBuilder and HashCodeBuilder as shown below with a simple equalsContract test method. When I run that equalsContract against the Apache builders, I get "java.lang.IlleagalStateException Precondition: both values are equal."
 

# What is the code that triggers this problem?

```
public class Source extends AuditEntity {
	private String owner;
	private String mark;
	private String source;

	// getters and setters

	@Override
	public int hashCode() {
		return new HashCodeBuilder()
				.append(this.mark)
				.append(this.source)
				.append(this.id)
				.toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if(this == obj) {
			return true;
		}
		if(!(obj instanceof AuditEntity)) {
			return false;
		}
		SourceQueue rhs = (SourceQueue) obj;
		return new EqualsBuilder()
				.append(this.ownerMark, rhs.getMark())
				.append(this.source, rhs.getSource())
				.append(this.terminalId, rhs.getId())
				.isEquals();
	}
}
```

```
	@Test
	public void equalsContract() {
		EqualsVerifier //.simple()
			.forClass(SourceQueue.class)
			.withPrefabValues(Inbound.class, new Inbound(), new Inbound())
                        // AuditEntity is an abstract class, Source extends AuditEntity
			.withPrefabValues(AuditEntity.class, new Source(), new Source())
			.verify();
	}

```

# What error message or stack trace does EqualsVerifier give?
java.lang.IllegalStateException: Precondition: both values are equal.
	at nl.jqno.equalsverifier.internal.util.Validations.validate(Validations.java:188)
	at nl.jqno.equalsverifier.internal.util.Validations.validateRedAndBluePrefabValues(Validations.java:66)
	at nl.jqno.equalsverifier.internal.util.PrefabValuesApi.addPrefabValues(PrefabValuesApi.java:17)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.withPrefabValues(SingleTypeEqualsVerifierApi.java:93)
	at com.chris.rms.profile.model.SourceTest.equalsContract(SourceTest.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

# What did you expect?
A single simple equals test:

```
	@Test
	public void testEquals() {
		Source s1 = new Source("one", "one", "one");
		Source s2 = new Source("one", "one", "one");
		
		assertTrue(s1.equals(s2));
	}
```

succeeds without error. The error I am getting, combined with the fact that for the moment I am using the Apache Commons EqualsBuilder feels like an issue buried in one of the two libraries, but I am not sure how to trace it down.

If I use the equals and hashcode methods generated by Eclipse, I get different errors from EqualsVerifier, and I am fully ready to believe that those errors stem from badly written methods.

# Which version of EqualsVerifier are you using?
I am using EqualsVerifier 3.4.1 and Apache Commons Lang3 3.5

# Please provide any additional information below.
1. When I started googling my issue, I was surprised to find [this](https://jqno.nl/equalsverifier/errormessages/precondition-two-objects-are-equal-to-each-other/),  because that link specifically mentions upgrading to v2.0, but as noted above, I am using 3.4.1!
2. My actual class has many more state values than the three I list here, but other than changing the names, the methods I have listed here are real. I am only using three properties in the equals and hashcode methods by deliberate choice.

**Comment by cptully** [comment]
And I forgot to mention the Source,class is NOT a Singleton. It is an object that get created many hundreds of times  in my application.

**Comment by jqno** [comment]
You're testing `SourceQueue`. I assume that's a class that uses `AuditEntity` in one of its fields. EqualsVerifier should probably be able to instantiate objects without using `withPrefabValues`, so you should probably be able to remove those lines under normal circumstances. If not, then you must make sure that the two instances of `AuditEntity` are NOT equal. Here, you give `new Source()` twice. I assume that the default constructor just leaves the fields empty, so it makes sense that `new Source().equals(new Source())`. In fact, you already assert that in your single simple equals test.

In other words, if you need to use `withPrefabValues` for `AuditEntity`, make sure you give it two different objects: `.withPrefabValues(AuditEntity.class, new Source("one", "one", "one"), new Source("two", "two", "two"))`

You can add a separate `EqualsVerifier.forClass(Source.class)` test to see if that has a correct implementation of `equals` and `hashCode` as well. Looking at the code you give for `Source`, which uses EqualsBuilder, I'd say that it probably will, although it will complain about [things not being final](https://jqno.nl/equalsverifier/manual/final/).

Let me know if that helps; if so we can close this issue.

**Comment by cptully** [comment]
Jan,

Thanks for the quick reply!

After reading your comments, I went back to basics:

```
	@Test
	public void equalsContract() {
		EqualsVerifier //.simple()
			.forClass(Source.class)
			.verify();
	}
```

And it still complained about a recursive data structure on Inbound.class so I added that PreFab line back in, Then it again complained:

java.lang.AssertionError: EqualsVerifier found a problem in class com.railinc.rms.profile.model.SourceQueue.
-> Recursive datastructure.
Add prefab values for one of the following types: AuditEntity.

Keep in mind from my sample above, the Source extends AuditEntity, and AuditEntity is an Abstract class, so I am back to a slightly different version of my test method, per your comments:

```
	@Test
	public void equalsContract() {
		EqualsVerifier //.simple()
			.forClass(Source.class)
			.withPrefabValues(Inbound.class, new Inbound(), new Inbound())
			.withPrefabValues(AuditEntity.class, new Source("one", "one", "one"), new Source("two", "two", "two"))
			.verify();
	}
```

Which gives the following error:

java.lang.AssertionError: EqualsVerifier found a problem in class com.chris.rms.profile.model.Source.
-> com.chris.rms.profile.model.AuditEntity$$DynamicSubclass$2096057945 cannot be cast to com.chris.rms.profile.model.Source

I even tried making the PreFab line for AuditEntity use two anonymous instances of AuditEntity instead of Source and I get the same error.

I read over this article: https://jqno.nl/equalsverifier/errormessages/classcastexception/

And, I think I now understand why I am getting the error I am getting, but not how to fix it...

AuditEntity is an Abstract class, so I cannot instantiate it directly.  And, feeding anonymous versions of it to withPreFabValues did not work.

I started poking around the EqualsVerifier manual and noticed the withOnlyTheseFields method and that did not change the result of the test. And, after more poking around the documentation, I have found a method that passes:

```
	@Test
	public void equalsContract() {
		EqualsVerifier.simple()
			.forClass(Source.class)
			.withOnlyTheseFields("owner", "Id", "source")
			.withPrefabValues(Inbound.class, new Inbound(), new Inbound())
			.withPrefabValues(AuditEntity.class, new Source("one", "one", "one"), new Source("two", "two", "two"))
			.verify();
	}
```

I'm not particularly happy with adding .simple() but that may be my only choice at this point. AuditEntity is the base class for multiple subclasses in addition to Source, Also, Source is used heavily in the application so I cannot change it willy-nilly. For the moment I am going to stick with my working test and go on, but I would love any feedback you have.

**Comment by jqno** [comment]
Indeed, if you get Recursive data structure errors, you need to use `withPrefabValues()`.

I agree that using `.simple()` feels unsatisfying. Unfortunately I can't really help you if you don't post a complete piece of code for the `Source` and `AuditEntity` classes that reproduces the issue, which I can copy and paste into my IDE to debug. Doesn't have to be the full class from your codebase: you can remove sensitive and irrelevant things, as long as it still reproduces the issue.

**Comment by cptully** [comment]
Thanks again for the quick replies! Even using simple() is better than no test at all, which is where I was on Monday. I will talk with my manager and think about what I can post publicly.  For the moment I have moved on to other tests that I have to create. I have lots of tests to back fill into an app that has no tests to speak of!

**Comment by jqno** [comment]
No problem. I agree, if you have to bring a large codebase under test, using `.simple()` is already way better than having no tests at all. You have bigger fish to fry, you can always come back to this later.

**Comment by jqno** [comment]
I'm going to clean up and close this issue. If you find yourself working on this again and need assistance, feel free to re-open this issue, or open a new one!
