### ISSUE TITLE
Abstract delegation: Role's equals method delegates to an abstract method:

### ISSUE THREAD

**Issue by BaruchDavid** [jqno/equalsverifier#374]
Hello, i'am testing typicaly hibernate entity.

**Which version of EqualsVerifier are you using?**
I am using EqualsVerifier 3.5

**What is the code that triggers this problem?**
```
@Entity
@ToString(exclude = "users")
@Getter @Setter
@NoArgsConstructor
public class Role implements Serializable {

	private static final long serialVersionUID = -2090774371747207972L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long roleId;
	
	private String name;
	
	@ManyToMany(mappedBy= "roles", fetch = FetchType.LAZY)
	private Set<User> users = new HashSet<>();

	public Role( String name) {
		super();
		this.name = name;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof Role)) {
			return false;
		}
		Role role = (Role) o;
		return name.equals(role.name);
	}

	@Override
    public int hashCode() {
        return Objects.hash(name);
    }
}
```
`
And when i test it:

```
@Test
    public void equalsHashCodeRoleContracts() {
        final User user1 = User.builder().userId(1L).email("test@.com").build();
        final User user2 = User.builder().userId(2L).email("test@.de").build();
        EqualsVerifier.forClass(Role.class)
                .withOnlyTheseFields("name")
                .withPrefabValues(User.class, user1, user2).verify();
    }
```
**What error message or stack trace does EqualsVerifier give?**

> > java.lang.AssertionError: EqualsVerifier found a problem in class some.package.domain.Role.
> -> Abstract delegation: Role's equals method delegates to an abstract method:
>  Receiver class org.hibernate.engine.spi.PersistentAttributeInterceptor$$DynamicSubclass$1356732524 does not define or inherit an implementation of the resolved method abstract readObject(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; of interface org.hibernate.engine.spi.PersistentAttributeInterceptor.
> 
> For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
> 
> 	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:269)
> java.lang.AssertionError: EqualsVerifier found a problem in class some.package.domain.Role.
> -> Abstract delegation: Role's equals method delegates to an abstract method:
>  Receiver class org.hibernate.engine.spi.PersistentAttributeInterceptor$$DynamicSubclass$1356732524 does not define or inherit an implementation of the resolved method abstract readObject(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; of interface org.hibernate.engine.spi.PersistentAttributeInterceptor.
> 
> For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
> 
> 	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:269)
> 	at some.package.domain.EqualsVerifierTest.equalsHashCodeRoleContracts(EqualsVerifierTest.java:16)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
> Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
> 	at nl.jqno.equalsverifier.internal.util.Assert.fail(Assert.java:75)
> 	at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractMethods(AbstractDelegationChecker.java:106)
> 	at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractDelegation(AbstractDelegationChecker.java:80)
> 	at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.check(AbstractDelegationChecker.java:39)
> 	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithoutExamples(SingleTypeEqualsVerifierApi.java:353)
> 	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:321)
> 	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:267)
> 	... 23 more
> Caused by: java.lang.AbstractMethodError: Receiver class org.hibernate.engine.spi.PersistentAttributeInterceptor$$DynamicSubclass$1356732524 does not define or inherit an implementation of the resolved method abstract readObject(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; of interface org.hibernate.engine.spi.PersistentAttributeInterceptor.
> 	at some.package.domain.Role.$$_hibernate_read_name(Role.java)
> 	at some.package.domain.Role.equals(Role.java:46)
> 	at nl.jqno.equalsverifier.internal.checkers.AbstractDelegationChecker.checkAbstractMethods(AbstractDelegationChecker.java:101)
> 	... 28 more
> 
> 
> Process finished with exit code -1

Role.java:46 is this line:
return name.equals(role.name);

**What did you expect?**
success

**Please provide any additional information below.**

I've start googled for this issue, and i found this:

https://github.com/jqno/equalsverifier/issues/138
Actually i should be fixed in the version 2.0.2?

**Comment by jqno** [comment]
> Role's equals method delegates to an abstract method:
> Receiver class org.hibernate.engine.spi.PersistentAttributeInterceptor$$DynamicSubclass$1356732524 does not define or inherit an implementation of the resolved method abstract readObject(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; of interface org.hibernate.engine.spi.PersistentAttributeInterceptor.

I don't see that `PersistentAttributeInterceptor` anywhere in your code, so it seems like your test is running inside some container. EqualsVerifier has no control over whatever code the container wants to generate, so the best move is probably to make sure EqualsVerifier runs outside of it, if possible.

**Comment by faritf** [comment]
@BaruchDavid @jqno Just got the same problem. This is because of code generated by [hibernate-enhance-maven-plugin](https://docs.jboss.org/hibernate/orm/5.0/topical/html/bytecode/BytecodeEnhancement.html). 
It replaces properties to getters in equals and hashCode methods on bytecode level during build:
```
private String name;

public String getName() {
    return this.$$_hibernate_read_name();
}

public String $$_hibernate_read_name() {
    if(this.$$_hibernate_getInterceptor() != null) {
        this.name = (String)this.$$_hibernate_getInterceptor().readObject(this, "name", this.name);
    }

    return this.name;
}

public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof Role)) {
        return false;
    }
    Role role = (Role) o;
    return this.$$_hibernate_read_name().equals(role.$$_hibernate_read_name());
}

@Transient
private transient PersistentAttributeInterceptor $$_hibernate_attributeInterceptor;

@Override
public PersistentAttributeInterceptor $$_hibernate_getInterceptor() {
    return interceptor;
}
```

**Comment by BaruchDavid** [comment]
i'am using indeed this plugin too. How could you see this generated code?
Seems to be a new issue for equalsverifier?

**Comment by faritf** [comment]
You can see generated code by decompiling generated .class file for this entity in your target/classes directory (I'm using IntellijIDEA and open file directly in IDE). 
Seems to be an issue for equalsverifier, but I'm not sure, still trying to debug and find where and why it fails exactly.

**Comment by faritf** [comment]
@jqno @BaruchDavid Probably this is not issue of EqualsVerifier! 
Actually exception thrown when entity's `equals` method called, because when EqualsVerifier constructs entity, if finds `PersistentAttributeInterceptor $$_hibernate_attributeInterceptor` field and creates a proxy, that called when `equals` called. Since PersistentAttributeInterceptor is an interface proxy fails with message 

> Receiver class org.hibernate.engine.spi.PersistentAttributeInterceptor$$DynamicSubclass$1356732524 does not define or inherit an implementation of the resolved method abstract readObject

Since readObject receives object, property name and actual value,  I got work around with mocking PersistentAttributeInterceptor:
```
public class TestRole {
    @Mock
    private PersistentAttributeInterceptor interceptor1;
    @Mock
    private PersistentAttributeInterceptor interceptor2;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
        
        when(interceptor1.readObject(any(), anyString(), any()).thenAnswer(i -> i.getArguments()[2]); // return the same value, that passed to this method
        when(interceptor2.readObject(any(), anyString(), any()).thenAnswer(i -> i.getArguments()[2]);
    }
    
    @Test
    public void equalsHashCodeRoleContracts() {
        final User user1 = User.builder().userId(1L).email("test@.com").build();
        final User user2 = User.builder().userId(2L).email("test@.de").build();
        EqualsVerifier.forClass(Role.class)
                .withOnlyTheseFields("name")
                .withPrefabValues(PersistentAttributeInterceptor.class, interceptor1, interceptor2) // this is how i inject mocks in each entity:)
                .withPrefabValues(User.class, user1, user2).verify();
    }
}
```

**Comment by jqno** [comment]
@faritf Thanks for looking into this! Finding an implementation of `PersistentAttributeInterceptor`, for example by mocking it, and then passing it to `withPrefabValues` is exactly the workaround I would suggest in this situation.

I wish I could offer something prettier, but inventing implementations for any interfaces or abstract classes that are called from equals or hashcode methods, especially when they're being generated through bytecode manipulation from some build plugin, is unfortunately way out of scope for EqualsVerifier :).

If you can manage somehow to disable the plugin while running the EqualsVerifier tests, then you wouldn't need this workaround.
