### ISSUE TITLE
Warning.PACKAGE_PRIVATE_NONFINAL_FIELDS

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#500]
```
EqualsVerifier found a problem in class com.xenoterracide.ppm.util.modelgraph.TestNode.
-> Mutability: equals depends on mutable field id.
Make the field final, suppress Warning.NONFINAL_FIELDS or use EqualsVerifier.simple()
```

of course the fix for this is obvious

```java
  @Test
  void equalsHashCode() {
    EqualsVerifier.forClass(TestNode.class)
      .suppress(Warning.NONFINAL_FIELDS)
      .withOnlyTheseFields("id")
      .verify();
  }
```

however a lot of frameworks can now reflect using package private setters

```java
  @Override
  public UUID getId() {
    return this.id;
  }

  void setId(UUID id) {
    this.id = id;
  }
```
reducing the likelihood of it not being effectively immutable for the developer of the app.

What I propose is being able to suppress this with something like 

```java
.suppress(Warning.PACKAGE_PRIVATE_NONFINAL_FIELDS)
```

but this would still fail, whereas the above would not

```java
  public void setId(UUID id) {
    this.id = id;
  }
```

**Comment by jqno** [comment]
Hi!

That's an interesting idea. However, EqualsVerifier looks at fields, not accessor methods. That means that adding something like Warning.PACKAGE_PRIVATE_NONFINAL_FIELDS can't check the setter in the way that you propose, and it becomes basically an alias for Warning.NONFINAL_FIELDS, which wouldn't add a lot of value.

Of course it would be possible to add logic to look at setters, but when a field is not final, there could be other methods that mutate the state of that field too, and EqualsVerifier would have to start checking those as well, which opens a can of worms better left closed, I think.

Either way, this seems more like the domain of [MutabilityDetector](https://github.com/MutabilityDetector/MutabilityDetector).
