### ISSUE TITLE
Overriden Kotlin data class property detected as not used in equals

### ISSUE THREAD

**Issue by koral--** [jqno/equalsverifier#506]
**Describe the bug**
I guess that a lot of code is synthesised here, so it may be not possible to handle this case by EqualsVerifier but I'm trying.

EqualsVerifier seems to not support cases where tested class is a Kotlin data class (with `equals` and `hashCode` implementations generated by Kotlin compiler) with overridden property.

`equals` decompiled to java looks like that:
```java
   public boolean equals(@Nullable Object var1) {
      if (this != var1) {
         if (var1 instanceof PathQueryCondition) {
            PathQueryCondition var2 = (PathQueryCondition)var1;
            if (Intrinsics.areEqual(this.path, var2.path) && Intrinsics.areEqual(this.getHttpMethod$mockwebserver_path_dispatcher(), var2.getHttpMethod$mockwebserver_path_dispatcher()) && Intrinsics.areEqual(this.queryParameterName, var2.queryParameterName) && Intrinsics.areEqual(this.queryParameterValue, var2.queryParameterValue)) {
               return true;
            }
         }

         return false;
      } else {
         return true;
      }
   }
```
`httpMethod` property is accessed via synthesised method.

**To Reproduce**
1. Checkout this commit: https://github.com/citibox/mockwebserver-path-dispatcher/commit/d8521656183f615f8ed0f55d8525f00863faec91 
It's located on the source branch of this PR: https://github.com/DroidsOnRoids/mockwebserver-path-dispatcher/pull/22
2. Invoke `pl.droidsonroids.testing.mockwebserver.PathQueryConditionTest#equals and hashCode match contract` test

**Code that triggers the behavior**
Class signature:
```kotlin
data class PathQueryCondition(
    internal val path: String,
    override val httpMethod: HTTPMethod,
    internal val queryParameterName: String? = null,
    internal val queryParameterValue: String? = null
) : HttpUrlCondition()
```
equals and hashCode are fully generated by kotlin compiler.
Superclass has only one field: `httpMethod`

call to EqualsVerifier:
`EqualsVerifier.forClass(PathQueryCondition::class.java).verify()`

**Error message**
```
EqualsVerifier found a problem in class pl.droidsonroids.testing.mockwebserver.condition.PathQueryCondition.
-> Significant fields: equals does not use httpMethod, or it is stateless.
```

**Expected behavior**
EqualsVerifier should not fail.

**Version**
`3.7.1`
There is `3.5.5` in the linked commit. However, I've also tried the newest version.

**Additional context **
You may ask why I'm verifying class of which equals and hashCode is autogenerated. Well, it was not always data class in the history of the project. But equality is used in the logic.

**Comment by jqno** [comment]
Hi,

From the error message, it appears that the `httpMethod` field isn't used by `equals`, but the decompiled code you posted does use it: `Intrinsics.areEqual(this.getHttpMethod$mockwebserver_path_dispatcher(), var2.getHttpMethod$mockwebserver_path_dispatcher())`
Although I wonder what exactly that `$mockwebserver_path_dispatcher()` part does. EqualsVerifier will change the value of `httpMethod` using reflection, but if that doesn't actually affect the outcome of `$mockwebserver_path_dispatcher()`, then EqualsVerifier will think that the field isn't used for some reason.

Unfortunately, I have virtually no experience with Kotlin, so I can't help you figure out what Kotlin is doing there.

Maybe you can work around the issue by using `.withIgnoredFields()`?

**Comment by koral--** [comment]
If I use ` EqualsVerifier.forClass(PathQueryCondition::class.java).withIgnoredFields("httpMethod").verify()` then assertion fails with:
```
java.lang.AssertionError: EqualsVerifier found a problem in class pl.droidsonroids.testing.mockwebserver.condition.PathQueryCondition.
-> Significant fields: equals should not use httpMethod, but it does.
```
Test passes when I use `.suppress(Warning.ALL_FIELDS_SHOULD_BE_USED)`. However, I don't want to ignore this field nor suppress warnings as it is really used.

Below is the more complete decompiled java code, according to it, that `mockwebserver_path_dispatcher ` method is just a plain getter. The field in terms of JVM is also there so the modification via reflection should work. However, I'm not sure how accurate is such a code. Kotlin is compiled directly JVM bytecode, not transpiled to Java. Decompilation may introduce subtle differences.

Feel free to close this ticket if you don't see anything which can be changed in EqualsVerifier.

```java
public final class PathQueryCondition extends HttpUrlCondition {
   @NotNull
   private final String path;
   @NotNull
   private final HTTPMethod httpMethod;
   @Nullable
   private final String queryParameterName;
   @Nullable
   private final String queryParameterValue;

   @NotNull
   public final String getPath$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher() {
      return this.path;
   }

   @NotNull
   public HTTPMethod getHttpMethod$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher() {
      return this.httpMethod;
   }

   @Nullable
   public final String getQueryParameterName$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher() {
      return this.queryParameterName;
   }

   @Nullable
   public final String getQueryParameterValue$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher() {
      return this.queryParameterValue;
   }

   public int hashCode() {
      String var10000 = this.path;
      int var1 = (var10000 != null ? var10000.hashCode() : 0) * 31;
      HTTPMethod var10001 = this.getHttpMethod$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher();
      var1 = (var1 + (var10001 != null ? var10001.hashCode() : 0)) * 31;
      String var2 = this.queryParameterName;
      var1 = (var1 + (var2 != null ? var2.hashCode() : 0)) * 31;
      var2 = this.queryParameterValue;
      return var1 + (var2 != null ? var2.hashCode() : 0);
   }

   public boolean equals(@Nullable Object var1) {
      if (this != var1) {
         if (var1 instanceof PathQueryCondition) {
            PathQueryCondition var2 = (PathQueryCondition)var1;
            if (Intrinsics.areEqual(this.path, var2.path) && Intrinsics.areEqual(this.getHttpMethod$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher(), var2.getHttpMethod$mockwebserver_path_dispatcher_mockwebserver_path_dispatcher()) && Intrinsics.areEqual(this.queryParameterName, var2.queryParameterName) && Intrinsics.areEqual(this.queryParameterValue, var2.queryParameterValue)) {
               return true;
            }
         }

         return false;
      } else {
         return true;
      }
   }
}
```

**Comment by jqno** [comment]
That code doesn't look like anything really strange is going on. I assume that `Intrinsics.areEqual()` does basically the same as `java.util.Objects.equals`?
Also, can you show me what the `HttpMethod` enum looks like when decompiled to Java?

**Comment by koral--** [comment]
> Intrinsics.areEqual() does basically the same as java.util.Objects.equals

The implementation is slightly different:
```java
    public static boolean areEqual(Object first, Object second) {
        return first == null ? second == null : first.equals(second);
    }
```
```java
    public static boolean equals(Object a, Object b) {
        return a == b || a != null && a.equals(b);
    }
```

> what the HttpMethod enum looks like when decompiled to Java?

```java
public enum HTTPMethod {
   ANY,
   GET,
   HEAD,
   POST,
   PUT,
   DELETE,
   CONNECT,
   OPTIONS,
   TRACE,
   PATCH;
}
```

**Comment by jqno** [comment]
Ah, I didn't know if a Kotlin enum would decompile to a native Java enum. Apparently it does :). It would be interesting to see what happens when we run EqualsVerifier on these decompiled classes. I'll try it out as soon as I have some time.

**Comment by kilink** [comment]
This is happening because of the way the abstract class [HttpUrlCondition ](https://github.com/citibox/mockwebserver-path-dispatcher/blob/d8521656183f615f8ed0f55d8525f00863faec91/dispatcher/src/main/kotlin/pl/droidsonroids/testing/mockwebserver/condition/HttpUrlCondition.kt#L12) is written, namely that it defines a property with a default value, and therefore gets a [backing field](https://kotlinlang.org/docs/properties.html#backing-fields) of ``httpMethod``. It's the httpMethod field in the HttpUrlCondition class that EqualsVerifier is discovering and complaining about, in some sense rightfully so.

The base class could be written as follows to avoid having the backing field generated:

```kotlin
abstract class HttpUrlCondition : Condition {
    internal open val httpMethod: HTTPMethod get() = HTTPMethod.ANY
}
```

or make the field property abstract:

```kotlin
abstract class HttpUrlCondition : Condition {
    internal abstract val httpMethod: HTTPMethod
}
```

or if HttpUrlCondition were an interface with a default getter:

```kotlin
interface HttpUrlCondition : Condition {
    internal val httpMethod: HTTPMethod get() = HttpMethod.ANY
}
```

Any of the above fixes the problem for me.

**Comment by jqno** [comment]
@kilink Thanks for figuring this out, I have little to no experience with Kotlin so I'm not sure I would have figured this out on my own. I'm surprised this hasn't come up earlier, it seems like a common thing to do in Kotlin?

@koral-- Does this solve your issue?

**Comment by koral--** [comment]
Yeah, I already applied the 1st proposed changed. Thanks @kilink

**Comment by borjab** [comment]
I had hit the same issue but the _internal_ workaround does not seem to use. 
Here is some example:

```
sealed class Base(
    internal open val type: String,
    internal open val extraType: Int,
) {
    fun myCommonLogic() { /* Common use of type and extraType */
    }
}

data class Type1(override val extraType: Int) : Base("type1", extraType)

data class Type2(override val extraType: Int) : Base("type2", extraType)

class Test {

   // Fails -> Significant fields: equals does not use extraType, or it is stateless
    @Test
    fun `Type1 fulfills equals contract`() {
        EqualsVerifier.forClass(Type1::class.java)
            .withIgnoredFields("type")
            .verify()
    }

     // Fails -> Significant fields: equals does not use extraType, or it is stateless
    @Test 
    fun `Type2 fulfills equals contract`() {
        EqualsVerifier.forClass(Type2::class.java)
            .withIgnoredFields("type")
            .verify()
    }

    @Test
    // Passes 
    fun `equals is working`() {
        val type11 = Type1(1)
        val type12 = Type1(2)
        val type21 = Type2(1)
        val type22 = Type2(2)

        assertThat(type11).isEqualTo(type11)
        assertThat(type12).isEqualTo(type12)
        assertThat(type21).isEqualTo(type21)
        assertThat(type22).isEqualTo(type22)

        assertThat(type11).isNotEqualTo(type12)
        assertThat(type11).isNotEqualTo(type21)
        assertThat(type11).isNotEqualTo(type22)

        assertThat(type12).isNotEqualTo(type11)
        assertThat(type12).isNotEqualTo(type21)
        assertThat(type12).isNotEqualTo(type22)

        assertThat(type21).isNotEqualTo(type11)
        assertThat(type21).isNotEqualTo(type12)
        assertThat(type21).isNotEqualTo(type22)

        assertThat(type22).isNotEqualTo(type11)
        assertThat(type22).isNotEqualTo(type12)
        assertThat(type22).isNotEqualTo(type21)
    }
}
```

Note that I cannot move type or subtype outside of the primary constructor. So at the end I can only use
`     .suppress(ALL_FIELDS_SHOULD_BE_USED) `


I would say that this is relatively frequent in Kotlin. It is just that this equals method is not as visible and there are less pressure to have higher coverage

**Comment by jqno** [comment]
Sorry for the late reply. The issue was already closed, so the notification got buried somewhere in my e-mail inbox during the holidays.

Anyway, thanks to your simple reproduction code, I was able to pinpoint the issue and find a solution. The problem was that unlike Java, Kotlin generates an `extraType` field _both_ in `Base` and in `Type1`/`Type2`, but since they have the same value, it only refers to `Type1.extraType` in `Type1`'s equals method. The error message you see, refers to `Base.extraType`, but since they have the same name, you can't see that in the error message, and you also can't explicitly ignore the one from `Base`.

I managed to find a way to detect when something is a Kotlin class, and in that case filter out the fields from superclasses with the same name. Hopefully that solves your issue, but if it doesn't don't hesitate to open a new ticket! It's just released in version 3.18.1.

**Comment by borjab** [comment]
@jqno, I can confirm that this fixes the issue. 

Thanks for your fast response. I really appreciate your great support and that fast release. 

P.S: I was checking if I could remove `withIgnoredFields("type")` but `type` is not part of the primary constructor and the autogenerated equals does not use it. (Validated in Bytecode). So EqualsVerifier is now working as expected.

**Comment by jqno** [comment]
Thanks for checking, glad to hear it's working for you now!
