### ISSUE TITLE
Fails for Abstract class

### ISSUE THREAD

**Issue by arvindkgs** [jqno/equalsverifier#513]
**Describe the bug**
When the object being compared contains a member variable that is abstract, EqualsVerifier.verify fails with error `Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class`

**To Reproduce**
import com.fasterxml.jackson.databind.JsonNode;
import lombok.Data;

@Data
class ClassToVerify {
	private JsonNode node;

	public void test() {
		EqualsVerifier.forClass(ClassToVerify.class).verify();
	}
}

I tried to exclude and suppress the error on the field as :
EqualsVerifier.forClass(ClassToVerify.class).withIgnoredFields("node").suppress(Warning.INHERITED_DIRECTLY_FROM_OBJECT).suppress(Warning.STRICT_INHERITANCE).verify();

**Error message**
Missing implementation of resolved method 'abstract boolean equals(java.lang.Object)' of abstract class com.fasterxml.jackson.databind.JsonNode

**Expected behavior**
Equals method should be covered in Sonarlint coverage tests

**Version**
3.7.1

**Comment by jqno** [comment]
EqualsVerifier tries to create instances of every field, but it can't if the class is abstract. Therefore, you have to give it prefab values so it can use those instead.
```
JsonNode node1 = ...; // fill in some value
JsonNode node2 = ...; // fill in another value
EqualsVerifier.forClass(ClassToVerify.class)
    .withPrefabValues(JsonNode.class, node1, node2)
    .verify();
```
The values you fill in can be of any subtype of `JsonNode` that you want, so by all means choose something that's easy to construct.
