### ISSUE TITLE
EqualsVerifier.forPackage fails in presence of classes with anonymous/local inner classes

### ISSUE THREAD

**Issue by kilink** [jqno/equalsverifier#517]
EqualsVerifier.forPackage picks up anonymous/local inner classes, which causes verification to fail.

Contrived example, we have a package ``net.kilink.example`` with a single class ``Thing.java``, which happens to have methods with inner anonymous and local class referrences:

```java

package net.kilink.example;

import java.util.Objects;
import java.util.function.Supplier;

public final class Thing {
    private String name;

    public Thing(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        return Objects.hash(name);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Thing)) return false;
        Thing thing = (Thing) o;
        return Objects.equals(name, thing.name);
    }

    public Supplier<String> nameSupplier() {
        return new Supplier<String>() {
            @Override
            public String get() {
                return name;
            }
        };
    }

    public Supplier<String> localClassNameSupplier() {
        class ThingNameSupplier implements Supplier<String> {
            @Override
            public String get() {
                return name;
            }
        }
        return new ThingNameSupplier();
    }
}
```

And then running EqualsVerifier like so:

```java
EqualsVerifier.forPackage("net.kilink.example").verify();
```

We end up with the following failures:

```
EqualsVerifier found a problem in class net.kilink.example.Thing$1ThingNameSupplier.
-> Equals is inherited directly from Object.
Suppress Warning.INHERITED_DIRECTLY_FROM_OBJECT to skip this check.

...

EqualsVerifier found a problem in class net.kilink.example.Thing$1.
-> Equals is inherited directly from Object.
Suppress Warning.INHERITED_DIRECTLY_FROM_OBJECT to skip this check.
```

Note that this happens regardless of whether the anonymous / local class is returned from the method.

This fails even worse in the presence of a Guava / Gson TypeToken anonymous class. I *think* the package scanner can simply skip anonymous and local classes to work around the issue; the test suite all passes with that change, and I am struggling to think fo a legitimate scenario for scanning these.

**Comment by jqno** [comment]
Thanks for the PR! I think it's a good idea to merge it, but maybe we can still add a test case for a synthetic class, as PITest suggests?

**Comment by kilink** [comment]
Thinking about it, in practice it can never be a synthetic class, which is a runtime generated class like a proxy. I've just removed the line filtering for synthetic classes altogether.

**Comment by jqno** [comment]
Sounds good!
Thanks for the PR. I've merged it and will let you know when I make a release.

**Comment by jqno** [comment]
Version 3.7.2 is syncing with Maven Central right now!
