### ISSUE TITLE
The `equalsverifier-3.8.1` tag is missing

### ISSUE THREAD

**Issue by Stephan202** [jqno/equalsverifier#555]
Title says it :) Right now `equalsverifier-3.8.1` isn't listed on the [tags page](https://github.com/jqno/equalsverifier/tags). This also breaks the associated link in the [changelog](https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md#381---2021-12-15) :)

**Comment by jqno** [comment]
Whoops, thanks for letting me know! It's fixed now.

You have a keen eye; I just realise that I didn't even announce this release yet 😅
