### ISSUE TITLE
ava.lang.AssertionError: EqualsVerifier found a problem in class ArtefactTypeEntity. -> Unsupported class file major version 61

### ISSUE THREAD

**Issue by GAskefalk** [jqno/equalsverifier#567]
**Describe the bug**
Running Equalsverifier on Java 17

**To Reproduce**
Take any class and run on Java 17

**Code that triggers the behavior**

/**
 * Created by Gerry Askefalk (ezaskge) on: 2018-07-23
 */
public abstract class AbstractEntityTest< T> {

    @Test
    @Disabled // does not yet support Java 17!
    public void equalsTest() {

        EqualsVerifier
                .forClass(((Class) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[0]))
                .usingGetClass()
                .verify();
    }

    @Test
    public void testAccesors_shouldAccessProperField() {

        validateAccessors((Class) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[0]);
    }
}

and then

/**
 * Created by Gerry Askefalk  on: 2019-07-04
 */
public class ArtefactTypeEntityTest  extends AbstractEntityTest<ArtefactTypeEntity> {

}

_Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!_

**Error message**
Se headline

**Expected behavior**
That it says my Equals is ok-

**Version**
What version of EqualsVerifier are you using? 3.1.9

**Additional context**

**Comment by jqno** [comment]
I see you're using EqualsVerifier 3.1.9. That version was released around the time of Java 13. If you upgrade to a more recent version of EqualsVerifier, the problem goes away.

**Comment by GAskefalk** [comment]
Ahh damned iu thought i checked all versions.

You are correct, thanks for the feedback.
