### ISSUE TITLE
3.9 sources missing on Maven Central

### ISSUE THREAD

**Issue by don-vip** [jqno/equalsverifier#598]
**Describe the bug**
Sources artifacts have not been published on Maven Central for the 3.9 release.

**To Reproduce**
Browse to https://repo1.maven.org/maven2/nl/jqno/equalsverifier/equalsverifier/3.9/

**Observed behavior**
No sources.

**Expected behavior**
Sources artifacts are present, like 3.8.3 release: https://repo1.maven.org/maven2/nl/jqno/equalsverifier/equalsverifier/3.8.3/

**Version**
3.9

**Comment by jqno** [comment]
You're right, and the Javadoc artefacts are also missing. Thanks for letting me know. I don't think I can fix this for 3.9 anymore, but I'll try to make sure they're back for the next release.

**Comment by jqno** [comment]
I've just released a new version, and the sources and javadoc jars are back now :)
