### ISSUE TITLE
Verify `Map.Entry::hashCode` contract

### ISSUE THREAD

**Issue by scordio** [jqno/equalsverifier#603]
**Is your feature request related to a problem? Please describe.**
We recently added a fix (assertj/assertj-core#2503) about a `hashCode` implementation that was not fulfilling the contract of [`Map.Entry::hashCode`](https://docs.oracle.com/javase/9/docs/api/java/util/Map.Entry.html#hashCode--).

The contract mentions:

> The hash code of a map entry e is defined to be:
>
>    (e.getKey()==null   ? 0 : e.getKey().hashCode()) ^
>    (e.getValue()==null ? 0 : e.getValue().hashCode())

Considering the class had already the following test:

```java
  @Test
  void should_honor_equals_contract() {
    // WHEN/THEN
    EqualsVerifier.forClass(MapEntry.class)
                  .verify();
  }
```

and the test was green, I assume EqualsVerifier is not verifying this aspect.

**Describe the solution you'd like**
Would it make sense to have this verification in the scope of EqualsVerifier?

**Describe alternatives you've considered**
A test has been introduced to enforce the behavior:

https://github.com/assertj/assertj-core/blob/main/src/test/java/org/assertj/core/data/MapEntry_Test.java#L39-L54

---

If the idea is accepted, I can try to put together a PR.

**Comment by jqno** [comment]
Hi! Thanks for telling me about this, I wasn't aware that Map.Entry has this extra requirement to its hashCode contract. So, indeed, EqualsVerifier doesn't check for this.

I'm a little in doubt about whether to add this, because I don't know if other classes don't have similar extra requirements, so I'm a bit worried about the extra work it would cause to be consistent in that regard (like, if EqualsVerifier supports this for Map.Entry, should it also support it for all of the other ones, and how many of them would be out there?)

On the other hand, I really like AssertJ and I'd love to help you out :).

Do you think adding this check would add a lot of extra code?

**Comment by scordio** [comment]
> Do you think adding this check would add a lot of extra code?

You're referring to EqualsVerifier codebase, right? I'm not really familiar with the internals but happy to have a look, learn and propose the change to better evaluate the impact 🙂 

On the other side, this is now covered in AssertJ with a few lines:

```java
  @ParameterizedTest
  @CsvSource({
    "name, Yoda",
    " , Yoda",
    "name, ",
    " , ",
  })
  void should_honor_Entry_hashCode_contract(String key, String value) {
    // GIVEN
    MapEntry<String, String> underTest = entry(key, value);
    int expected = Objects.hashCode(key) ^ Objects.hashCode(value);
    // WHEN
    int result = underTest.hashCode();
    // THEN
    then(result).isEqualTo(expected);
  }
```

so we could live with it, but I raised this issue in case this verification could be beneficial to others.

> if EqualsVerifier supports this for Map.Entry, should it also support it for all of the other ones, and how many of them would be out there?

I think a pragmatic approach could be ok, `Map.Entry` belongs to the JDK and it would be the first case supported on top of the contract defined by `Object`. I'm not really aware of other cases but I'm no JDK expert. I would expect users to raise similar issues if they find some other good candidates.

Totally your call, of course!

**Comment by jqno** [comment]
OK then, let's do this :smiley: .

I follow a similar approach with built-in prefab values, where I add a prefab value for a JDK class when someone asks for it; I don't go hunting for them myself. I suspect the number of additional hashCode contract requirements will be a lot less than that of classes for which I need to add prefab values.

I'd be happy to see your proposal, and please let me know if I can help. I think creating a separate AdditionalHashCodeRequirementChecker would be a good first step. (I feel like we should be able to come up with a better name for it, too :sweat_smile: )

**Comment by scordio** [comment]
Thanks! I try to do my homework and I'll bother you if I'm stuck 🙂

**Comment by jqno** [comment]
Thank you for doing the work. Don't worry about bothering me!

**Comment by jqno** [comment]
Hi there! Any updates? 🙂

**Comment by scordio** [comment]
Whoops, this definitely slipped under my radar 😅 sorry about that.

I would still like to contribute to this. I'll catch up with it during the week and come back to you!

**Comment by jqno** [comment]
Haha, no worries, there's no rush. I was just going though my backlog and found this issue :)
