### ISSUE TITLE
Update byte-buddy to 1.12.8

### ISSUE THREAD

**Issue by kebeda** [jqno/equalsverifier#611]
Mockito now uses 1.12.8, which causes a RequireUpperBoundDeps enforcer error when used with equalsverifier 3.9

**Comment by jqno** [comment]
The next release will have Byte Buddy 1.12.8 (or higher, if a new version appears before then 😄). I have to fix another bug before I can release, though.

In the mean time, you can switch to the `equalsverifier-nodep` artifact, which embeds all dependencies.

**Comment by kebeda** [comment]
Awesome, thank you!

**Comment by jqno** [comment]
I've just released version 3.9.1, which updates the dependency.
