### ISSUE TITLE
100% coverage issue with Lombok

### ISSUE THREAD

**Issue by MarkPrucnal18** [jqno/equalsverifier#673]
I'm currently working on a project that is using the Lombok @EqualsAndHashCode annotation. I looked at the "Coverage is not 100%" error page and saw that there was a specific issue with Lombok. It looks like that error listed only affects the equals methods. I currently am using this for my mutation coverage and it is hitting all of the Equals methods but not all of the HashCode methods. I tried the Lombok fix but nothing change when I implemented it. The line of code I'm currently using is **EqualsVerifier.simple().forClass(nameOfClass.class).verify();** Do you have any recommendations on how to fix this issue?

**Comment by jqno** [comment]
I'm sorry, I don't have a lot to go on here. EqualsVerifier has a bunch of integration tests that check the coverage, which all pass. Also, there's no branching in Lombok's generated hashCode methods, so I don't understand how it's even possible that it covers "not all of" the hashCode methods.

Can you share the code for the class where you don't get full coverage, so I can take a look?

**Comment by MarkPrucnal18** [comment]
Here is the code of the class I am working with. just underneath that is the test that I'm using.

`@Getter
@Setter
@EqualsAndHashCode
@JsonIgnoreProperties(value = {"createdTimestamp", "lastUpdatedTimestamp"})
@DynamoDBTable(tableName = "OutsideContributionData")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OutsideContributionsRecord {

    @DynamoDBHashKey
    private String partitionKey;

    @DynamoDBRangeKey
    @DynamoDBTypeConvertedEnum
    private ContributionsSortKey sortKey;

    @DynamoDBAttribute
    private String profileId;

    @DynamoDBAttribute
    private String consumerId;
    /*
     * Outside contributions record was created
     * on behalf profileId (in the url path) by lastUpdateByUser
     */
    @DynamoDBAttribute
    private String lastUpdateByUser;

    @DynamoDBIgnore
    private List<Contribution> contributions;

    @DynamoDBAttribute
    private List<Contribution> iraContributions;

    @DynamoDBAttribute
    private List<Contribution> hsaContributions;

    @DynamoDBAttribute
    private List<Contribution> contributions529;

    @DynamoDBVersionAttribute
    private Long version;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdTimestamp;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date lastUpdatedTimestamp;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    private Map<String, Object> metadata;
}`

`@Test
    void equalsAndHashCode() {
        EqualsVerifier.simple().forClass(OutsideContributionsRecord.class).verify();
    }`
    
    
The following images will show the following mutation coverage for this code
![image](https://user-images.githubusercontent.com/109984320/181018542-275ec5e8-9291-47d7-b42e-468bf826929d.png)

![image](https://user-images.githubusercontent.com/109984320/181018795-266862f3-a3c8-4ee2-9d56-64b8bcae9f3a.png)
All equals are being covered^^^

![image](https://user-images.githubusercontent.com/109984320/181019027-eba7be7e-59b3-4bc7-8838-495b92841ce5.png)
Some, but not all, HashCodes are being covered

**Comment by jqno** [comment]
Ah, you're talking about mutation test coverage. The promise of 100% coverage only applies to traditional test coverage. I've added a note about that to the website, but it comes down to this:

Mutation testing will change operators like `*` and `+` in the `hashCode` implementation into other operators and check if the tests then fail, which they often don't. The only way to get 100% mutation coverage, is to "pin down" the hashCode to a specific value, which is a form of [overfitting](https://en.wikipedia.org/wiki/Overfitting). Therefore, it's not desitable to have 100% mutation coverage on `hashCode`.

**Comment by jqno** [comment]
By the way, this is not specific to Lombok; this will happen with hand-written `hashCode` and with `hashCode` generated by the IDE as well.

**Comment by MarkPrucnal18** [comment]
ok, thank you for your input.
