### ISSUE TITLE
Allow filtering forPackage with type

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#706]
See https://github.com/jqno/equalsverifier/issues/697#issuecomment-1249306797 for context

>  use forPackage is if I could do some kind of forPackageWithType("my.package", AbstactClassOrInterface.class) so that I could scan but check only things of that type.

This would be incredibly useful for things like scanning entities and aggregates that have an abstract base class or a common interface. I'm not sure how to fit recursive in here... but given that I would probably always use it that way with a filter.

**Comment by jqno** [comment]
So, to make it specific: EqualsVerifier would only check classes that are
a) in the specified package, AND
b) implement or extend the given class.

**Comment by jqno** [comment]
I've just added this in version 3.11, which is now syncing with Maven Central.
