### ISSUE TITLE
Im using JDK 17 and EqualsVerifier version 3.10.1 and get Unsupported class file major version 61 error

### ISSUE THREAD

**Issue by srihitha97** [jqno/equalsverifier#732]
**Describe the bug**
I have a testcase that uses EqualsVerifier, I have migrated from JDK 8 to JDK 17 after which I get the `Unsupported class file major version 61 error`, and then I upgraded EqualsVerifier from version 3.1 to 3.10.1 and am still getting the same error.

**To Reproduce**
Use JDK 17 and EqualsVerifier 3.10.1

**Code that triggers the behavior**
```
    @Test
    public void verifyEqualsAndHashCode() {
        EqualsVerifier.forClass(PointOnTheChain.class)
                .withIgnoredFields("chainSeqno", "representsAChainTransition")
                .withNonnullFields("chainTimeNanos")
                .verify();
    }
```

**Error message**
What error message or stack trace does EqualsVerifier give?
```
junit.framework.AssertionFailedError: EqualsVerifier found a problem in class xyz.
[junit]      -> Unsupported class file major version 61
[junit]     
[junit]          at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(Unknown Source)
[junit]          at xyz.verifyEqualsAndHashCode(test.java:102)
[junit]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[junit]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[junit]          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[junit]      Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
```

**Expected behavior**
Test case should pass like before without any error.

**Version**
What version of EqualsVerifier are you using?
3.10.1

**Additional context**
 I have also tried using the Maven-nl-jqno-equalsverifier_equalsverifier-nodep jar, I still get the same error.

**Comment by jqno** [comment]
Hi!
EqualsVerifier works fine on JDK 17, I use it there all the time. Are you sure you're using version 3.10.1? Can you double check with `mvn dependency:tree` or `gradle dependencies`? Maybe it's in there twice or something.
If not, I see that you trimmed the stacktrace, can you post the full thing? The interesting stuff is often near the bottom.

**Comment by srihitha97** [comment]
@jqno Sure, this is the entire stacktrace:
```
[junit]      Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.062 sec
[junit]     
[junit]      Testcase: verifyEqualsAndHashCode(xyz):    FAILED
[junit]      EqualsVerifier found a problem in class xyz.
[junit]      -> Unsupported class file major version 61
[junit]     
[junit]      For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
[junit]      junit.framework.AssertionFailedError: EqualsVerifier found a problem in class xyz.
[junit]      -> Unsupported class file major version 61
[junit]     
[junit]          at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(Unknown Source)
[junit]          at aws.journal.archiver.state.PointOnTheChainTest.verifyEqualsAndHashCode(Test.java:102)
[junit]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[junit]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[junit]          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[junit]      Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
[junit]          at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:195)
[junit]          at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:176)
[junit]          at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:162)
[junit]          at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
[junit]          at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1174)
[junit]          at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1160)
[junit]          at net.bytebuddy.pool.TypePool$AbstractBase.describe(TypePool.java:408)
[junit]          at net.bytebuddy.pool.TypePool$AbstractBase$Hierarchical.describe(TypePool.java:471)
[junit]          at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.build(Unknown Source)
[junit]          at nl.jqno.equalsverifier.internal.util.Configuration.buildAnnotationCache(Unknown Source)
[junit]          at nl.jqno.equalsverifier.internal.util.Configuration.build(Unknown Source)
[junit]          at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(Unknown Source)
[junit]          at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(Unknown Source)
```

**Comment by jqno** [comment]
Thanks, but first, what about the dependency tree?

**Comment by srihitha97** [comment]
> Thanks, but first, what about the dependency tree?

I am currently using happytrails (internal) as my build-system so the above commands don't work for getting the dependencies, I need to look into how I can get the dependency tree.

Is there any other way to see if it is present twice, or some command to clean it and rebuild the dependencies?

**Comment by jqno** [comment]
I don't know how to do that outside of the build system, unfortunately.
But please let me know if you figure it out. I've seen this kind of problem before and usually it happens because somehow an older version of EqualsVerifier is also on the classpath and wins out for some reason.

**Comment by jqno** [comment]
Just as an FYI, in version 3.12 I added some version info to the EqualsVerifier error messages. So if you update to 3.12 and you *don't* see that text, you'll know that you're indeed using an older version somehow. Maybe that will help you figure this out.

**Comment by sparsick** [comment]
Hi,

same issue here. My error message is

```shell
EqualsVerifier found a problem in class com.github.sparsick.test.tool.database.Person.
-> Unsupported class file major version 61

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.12.3, JDK 17 on Linux)

```

The sample can be found https://github.com/sparsick/test-tool-talk/tree/jdk17

**Comment by jqno** [comment]
Thanks for the sample project. I can reproduce the issue. Strange! I'll have to investigate why this happens, I'll get back to you...

**Comment by jqno** [comment]
OK, I figured it out. I'll highlight from `mvn dependency:tree`:

```
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.4.3:test
[INFO] |  +- org.mockito:mockito-core:jar:3.6.28:test
[INFO] |  |  \- net.bytebuddy:byte-buddy-agent:jar:1.10.20:test
[...]
[INFO] +- nl.jqno.equalsverifier:equalsverifier:jar:3.12:test
[INFO] |  +- org.objenesis:objenesis:jar:3.3:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.10.20:test
```

I know that EqualsVerifier 3.12 depends on Byte Buddy 1.12.something, but the version brought in (indirectly) by spring-boot-starter-test overrides that to an old version. So there's a couple things you can do to fix it:

- Update spring-boot-starter-test and hope the most recent version has appropriate dependencies.
- Override the version of byte-buddy in your Maven pom and maintain it manually.
- Switch to the `equalsverifier-nodep` dependency, which has an appropriate version of byte-buddy shaded into its jar.

The last option is kind of dirty, but by far the easiest one to achieve :sweat_smile:

**Comment by sparsick** [comment]
Thank you. So my plan firstly update the jdk and then make the update for Spring Boot was the "wrong" one. 😅
