### ISSUE TITLE
Git tag for version 3.12 missing

### ISSUE THREAD

**Issue by Stephan202** [jqno/equalsverifier#741]
Good morning @jqno! Just a friendly heads-up: version 3.12 was released recently, but it appears that the associated tag wasn't pushed. As a result the [diff link](https://github.com/jqno/equalsverifier/compare/equalsverifier-3.11.1...equalsverifier-3.12) contained in the [changelog](https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md#312---2022-11-30) doesn't work.

**Comment by jqno** [comment]
Nice catch, thank you! Fixed! :sweat_smile:

**Comment by Stephan202** [comment]
@jqno looks like tag `equalsverifier-3.12.3` is also a bit shy :eyes:

**Comment by jqno** [comment]
Again :roll_eyes: 
Sorry about that, thanks for reporting this!
As you [may have seen](https://github.com/jqno/equalsverifier/pull/731), I'm planning to automate these releases soon, so that this should no longer be an issue :sweat_smile:
