### ISSUE TITLE
Add test case that checks consistency of equalsIgnoreCase()

### ISSUE THREAD

**Issue by gsaviane** [jqno/equalsverifier#748]
In some equals() implementation you can find string fields compared ignoring the case. If, for instance, you have such implementation of equals() and hashCode()
`
![image](https://user-images.githubusercontent.com/12230922/209340938-c04bcbc2-c0b0-4326-91c8-3814e6e7de02.png)
`
The contract is broken, because two class instances with inst1.field= "AAA" and inst2.field = "aaa" would be equal but with different hashCode().

I propose to create a test case that checks in case equals() fires on strings that differ only on case, hashCode() must be consistent

**Comment by jqno** [comment]
That's a good idea.

I don't have a lot of time to spend on EqualsVerifier these days though, so it might be a little while before I get to it. I'll keep you posted. I'm open to PR's though :slightly_smiling_face:

**Comment by jqno** [comment]
I've added the test case in version 3.13.2, which is now syncing with Maven Central!

**Comment by gsaviane** [comment]
Great! Thanks to pick it up

Giorgio

Il giorno gio 16 feb 2023 alle ore 11:08 Jan Ouwens <
***@***.***> ha scritto:
