### ISSUE TITLE
Unable to use equalsverifier with Java 19 even if project is compiled to Java 17

### ISSUE THREAD

**Issue by stawirej** [jqno/equalsverifier#762]
**Describe the bug**

  java.lang.AssertionError:
    EqualsVerifier found a problem in class com.Id.
    -> Unsupported class file major version 63
    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
    (EqualsVerifier 3.13, JDK 19.0.1 on Mac OS X)

In pom.xml file
```
  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
```
to compile project to java 17 even if Java 19 is used. (Same if source and target is 19)

**To Reproduce**
Steps to reproduce the behavior

EqualsVerifier.forClass(Id.class).verify();

Id class is simple class containing single String field.

EqualsVerifier 3.13, JDK 19.0.1
Project compiled to java 17 or java 19 reports error.

**Code that triggers the behavior**
Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

_Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!_

**Error message**
What error message or stack trace does EqualsVerifier give?

  java.lang.AssertionError:
    EqualsVerifier found a problem in class com.Id.
    -> Unsupported class file major version 63
    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
    (EqualsVerifier 3.13, JDK 19.0.1 on Mac OS X)

**Expected behavior**

**Version**
What version of EqualsVerifier are you using?
EqualsVerifier 3.13

**Additional context**

**Comment by jqno** [comment]
Can you give me the output of `mvn dependency:tree`? I suspect you may have different versions of Byte Buddy on the classpath.

**Comment by stawirej** [comment]
❯ mvn dependency:tree | grep buddy
[INFO] |  |  \- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.10.22:test

**Comment by jqno** [comment]
Yeah, that's a pretty old version. You either have to upgrade whatever dependency that brought in that version of Byte Buddy, or you can switch to the `equalsverifier-nodep` artifact for a jar of EqualsVerifier that contains the correct version of Byte Buddy.

Just out of curiosity, can you tell me what it is that brought in that version of Byte Buddy?

**Comment by stawirej** [comment]
```
❯ mvn dependency:tree | grep -B 3 -A 3 buddy
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |  +- org.mockito:mockito-core:jar:3.9.0:test
[INFO] |  |  \- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.9.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
--
[INFO] +- net.jqwik:jqwik-time:jar:1.7.1:test
[INFO] +- nl.jqno.equalsverifier:equalsverifier:jar:3.13:test
[INFO] |  +- org.objenesis:objenesis:jar:3.3:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.10.22:test
[INFO] +- io.vavr:vavr:jar:0.10.4:compile
[INFO] |  \- io.vavr:vavr-match:jar:0.10.4:compile
[INFO] +- pl.amazingcode:timeflow:jar:1.4.0:compile
```

**Comment by stawirej** [comment]
Thank you for your rapid replay and help! That solved the issue :)

**Comment by jqno** [comment]
Glad to help!
