### ISSUE TITLE
Rounding for Double and Float are not covered for overloaded equals

### ISSUE THREAD

**Issue by kiryldz** [jqno/equalsverifier#806]
**Describe the bug**
Although https://github.com/jqno/equalsverifier/blob/main/docs/_errormessages/double-equals-doesnt-use-doublecompare-for-field-foo.md are correct to cover NaN cases, rounding issues are still the case.

**To Reproduce**

Sample class we're going to test:
```kotlin
class A(
  val a: Double
) {
  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (javaClass != other?.javaClass) return false
    other as A
    return a.compareTo(other.a) == 0
  }
  override fun hashCode(): Int {
    return Objects.hash(a)
  }
}
```

Equals-hash-code passes:
```kotlin
  @Test
  fun `A hashCode and equals test`() {
    EqualsVerifier.forClass(A::class.java)
      .usingGetClass()
      .verify()
  }
```

However results for comparing actual class instances are not consistent:
```kotlin
    val a1 = A(.1 + .1 + 10 * .1)
    val a2 = A(.1 + .1 * 10 + .1)

    val a3 = A(1.2)
    val a4 = A(1.2)

    println("Classes a1 and a2 equal: ${a1 == a2}") // false
    println("Classes a3 and a4 equal: ${a3 == a4}") // true
```

**Code that triggers the behavior**
Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

_Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!_

**Error message**
-

**Expected behavior**
Classes a1 and a2 are actually equal.

**Version**
`3.14`

**Additional context**
There is an [article](https://levelup.gitconnected.com/double-equality-in-kotlin-f99392cba0e4) what are the options to fix the rounding issue however I do not have the strong opinion what's the best way to wrap it in this library. The problem right now that if implement proper Double comparison using some extension function for example:
```kotlin
fun Double.equalsDelta(other: Double) = abs(this/other - 1) < 0.000001
```
Then the equalsverify test will actually fail and ask to use `compareTo`.

**Comment by jqno** [comment]
Thanks for raising this issue and giving me something to think about.

In principle I agree with you, that if you compare floats and doubles, you should use a delta.

However, in the case of equals, it's a bit harder. There are two things that the article doesn't discuss: how to deal with NaN, and how to deteremine a hashCode. The first one is relatively easy: comparing deltas will always result in false when one or both of the values are NaN, which is fine. If you want to return true if both values are NaN (which compareTo does), you can hard-code it.

The case of hashCode is more difficult, and to be honest I don't see a solution for it either. Following your example:
```
    val a1 = A(.1 + .1 + 10 * .1) // 1.2 -> Objects.hash(1.2) == 213909535
    val a2 = A(.1 + .1 * 10 + .1) // 1.2000000000000002 -> Objects.hash(1.2000000000000002) == 213909542
```
As you can see, the two values aren't the same, so it makes sense that equals returns false when you compare them. As a result, they also give different hashCodes. You could factor in the delta when determining the hashCode to make them return the same hashCode, but what do you do with 1.2000000000000004, 1.2000000000000006, 1.2000000000000008, etc? You run into transitivity problems.

I don't know a solution to this problem, apart from just returning a constant hashCode. But then the same transitivity issue will come up when running equals itself. If you know a solution for this, I'm very much open to it!

**Comment by jqno** [comment]
I've added something to the website: https://jqno.nl/equalsverifier/errormessages/double-equals-doesnt-use-doublecompare-for-field-foo/

**Comment by kiryldz** [comment]
@jqno thanks a lot for explanation! 🙇 I totally agree with your points and after giving this some thought I also don't have ideas how to fix transitivity issue and moreover for particularly hashCode use-case it's indeed not even needed - so sticking to `compareTo` seems to be the right option.

Closing this one.

**Comment by jqno** [comment]
Thanks! And if you do come up with a better way, please let me know and I'll try to find a way to integrate it into EqualsVerifier!
