### ISSUE TITLE
Please also support compareTo

### ISSUE THREAD

**Issue by PowerStat** [jqno/equalsverifier#866]
**Is your feature request related to a problem? Please describe.**
I am also writing open source classes (value objects) at https://github.com/PowerStat/Validation/tree/master/src/main/java/de/powerstat/validation/values - so I have already written a lot of hash/equals test code as well as compareTo (Comparable interface). So it would be helful to have this also supported.

**Describe the solution you'd like**
Support for Comparable interface / compareTo.

**Describe alternatives you've considered**
Until now I have written them all manually and verified with jacoco.

**Additional context**
See https://github.com/PowerStat/Validation
Btw. great job you did, I will rewrite my has/equal tests in the next days ;-)

**Comment by jqno** [comment]
It's a good idea that I've thought about before, but it's a big project and I just don't have the bandwidth to take it on. I think it would be better as a separate tool anyway.
