### ISSUE TITLE
Please add info about module requires for equalsverifier to the documentation.

### ISSUE THREAD

**Issue by PowerStat** [jqno/equalsverifier#867]
**Describe the bug**
Within the documentation there is no hint about the requires for the module-info.test

**Expected behavior**
Just add after the maven dependency:

module-info.test:

module com.example.tests
 {
  requires nl.jqno.equalsverifier;
 }

**Comment by jqno** [comment]
To be honest, I have no experience running EqualsVerifier on the module path. Can you show me how to do that, so I can try it for myself before updating the docs?

**Comment by PowerStat** [comment]
As you already found out please use my project with described modifications from #868.

**Comment by jqno** [comment]
I've added a section in the manual for this: https://jqno.nl/equalsverifier/manual/jpms/

I've also added some explanation about for the (new) error messages: https://jqno.nl/equalsverifier/errormessages/class-or-field-is-not-accessible-jpms/
