### ISSUE TITLE
equalsVerifier fails to validate final entity class with @GeneratedValue id

### ISSUE THREAD

**Issue by EagerSloth** [jqno/equalsverifier#929]
**Describe the bug**
Since version 3.15.5 equalsVerifier fails to validate one of my entity classes.

**Code that triggers the behavior**
Entity class:
```
@Entity
public final class JpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JpaEntity that = (JpaEntity) o;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
```

test case:
```
    @Test
    void equals() {
        EqualsVerifier.forClass(JpaEntity.class)
                .suppress(Warning.IDENTICAL_COPY_FOR_VERSIONED_ENTITY)
                .suppress(Warning.STRICT_HASHCODE)
                .suppress(Warning.SURROGATE_KEY)
                .verify();
    }
```

_Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!_

**Error message**
java.lang.AssertionError: EqualsVerifier found a problem in class com.whitewall.integrationapi.order.domain.JpaEntity.
-> Cannot subclass primitive, array or final types: class com.whitewall.integrationapi.order.domain.JpaEntity

**Expected behavior**
The test should still pass as in prior version - or give a hint how to fix the test.
The exception disappears when also suppressing `Warning.JPA_GETTER` - but I am not sure about the implications.

**Version**
Test OK in 3.15.4. fails in 3.15.5 - 3.15.7

**Comment by jqno** [comment]
Found the problem. EqualsVerifier considers a field marked with `@GeneratedValue` to be lazy, and applies its lazy field checks for that field. In that case, it assumes the entity is non-final (because Hibernate would also create a subclass to handle lazy loading of those fields). Your entity, however, is final. I didn't know that was allowed when there's a field with `@GeneratedValue`, but I'll just assume that it is, since you're obviously using that :smile: 

I've found a fix, too. I'll make a release later today.

**Comment by jqno** [comment]
Version 3.15.8 is syncing with Maven Central now, it should fix your problem!

**Comment by EagerSloth** [comment]
Thank you for the quick fix - confirming this solves our problem.

**Comment by jqno** [comment]
Awesome, glad to hear it!
