### ISSUE TITLE
support auto subclassing with `canEqual`

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#931]
**Is your feature request related to a problem? Please describe.**

```
        java.lang.AbstractMethodError: Receiver class com.xenoterracide.jpa.AbstractUuidDomainId$$DynamicSubclass$13e3c1c7$ does not define or inherit an implementation of the resolved method 'abstract boolean canEqual(com.xenoterracide.jpa.AbstractUuidDomainId)' of abstract class com.xenoterracide.jpa.AbstractUuidDomainId.
```

**Describe the solution you'd like**

This feels like something that could be done without prefab, although maybe not

I'm thinking that adding something like `withCanEqual()` method call to implement out subclasses would work.

https://jqno.nl/equalsverifier/errormessages/abstract-delegation/

https://github.com/xenoterracide/spring-app-commons/commit/030eb38560ea50d2e0904f06cbbeb2461724a6d1

**Comment by jqno** [comment]
If I understand correctly, you're trying to test an abstract class which has an abstract `canEqual` method, is that right? Or are you also seeing this when you test one of its subclasses?

And the question is, can't EqualsVerifier handle this case by itself, by stubbing out the `canEqual` method?

There's nothing in EqualsVerifier (or elsewhere) that says that this method is required to have the name `canEqual`, or to have the signature that it has. There are other ways to achieve the same behavior as well (see https://drdobbs.com/jvm/java-qa-how-do-i-correctly-implement-th/184405053 ). If I want to support all that, It'll open a can of worms I'm not sure I want to open.

Can you work around it by creating a subclass in your tests that does nothing except fill in the `canEqual` method? Or is there a reason that doesn't work for your particular case?

**Comment by xenoterracide** [comment]
> If I understand correctly, you're trying to test an abstract class which has an abstract canEqual method, is that right? Or are you also seeing this when you test one of its subclasses?

correct

> Can you work around it by creating a subclass in your tests that does nothing except fill in the canEqual method? Or is there a reason that doesn't work for your particular case?

that's what I did, I was just hoping to avoid prefabs all the way down.

> If I want to support all that, It'll open a can of worms I'm not sure I want to open.

that's fair, it's just a suggestion. This isn't blocking any behavior for me.

> that's what I did, I was just hoping to avoid prefabs all the way down.

that sparked an idea. Generally this is the only abstract method, which means I could generally fill it in with a lambda if the interface was right. Perhaps that's something you could help with via judicious use of generics? instead of passing in an instance, I could pass a lambda (I think that'll work for protected abstracts too... haven't tested).

**Comment by jqno** [comment]
You can avoid the prefabs all the way down problem with a configuration:

```
var ev = EqualsVerifier.configure().withPrefabValues(...);
ev.forClass(Foo.class).verify();
ev.forClass(Bar.class).verify();
```

Or you could use `forPackage()`:

```
EqualsVerifier.forPackage("com.example.model", AbstractEntity.class)
    .withPrefabValues(...)
    .verify();
```

That will run EqualsVerifier for all classes in the given package that also extend `AbstractEntity`. `forPackage()` has some more overloads as well, that might be of help.
