### ISSUE TITLE
Respect Nullity annotations

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#936]
I'm spitballing here, but there's some new work in the null checks world, and some other work. The general presumption moving forward for most people is that we should consider non null to be the default.

A lot of people though seem to be hoping/waiting on https://jspecify.dev which has an annotation `@Nullmarked` that you can put to decide that you've defined that. You might want to weigh in if you decide you like the idea of supporting nullity annotations. I think you probably should because I doubt you want to check a JPMS module whether it's `@Nullmarked` or a package.

For example, I have this on my `abstract`

```java
  private @NonNull ID id;

  protected AbstractEntity() {}

  protected AbstractEntity(@NonNull ID id) {
    this.id = id;
  }
  
  @Id
  @Override
  public @NonNull ID getId() {
    return this.id;
  }

  @Initializer
  void setId(@NonNull ID id) {
    this.id = id;
  }
```

This is over annotated per jspecify, but no one really supports that spec yet, nullaway supports non null by default, but intellij doesn't and wants it marked. Nullaway supports any annotation named `@Initializer` to be a framework called lazyinit, so it's still safe to consider id non null always. Unfortunately jspecify is refusing to handle lazyinit right now.

Anyways, you could use this to determine whether you have to check for null states. I'd check the name only, and case insensitive. As old annotations were `@Nonnull` and there's at least half a dozen vendors now. `@NonNull` and `@Nullable` are what's common.

Just thoughts. Could have some kind of a wither `for..(Class).isNullMarked()` with a javadoc pointing to jspecify by default, or `isNonNullByDefault` or something like that. Note: `NotNull` from the validation spec is a runtime validation, and should not be used.

**Comment by jqno** [comment]
That looks like a cool project, I hadn't seen it before. Everything is still in draft, do you know how stable it is, and whether people are already actually using it? Are you using it?

If I understand correctly, the idea is that you put a `@NullMarked` annotation on a class, and then all fields in the class should never be null (unless it's marked with `@Nullable`). If that's true, I think for EqualsVerifier, it would be enough to look for the `@NullMarked` annotation on a class in the same way that it already looks at `@NotNull`/`@NonNull`, which behave in much the same way.

**Comment by xenoterracide** [comment]
I'm using it, according to them the compile time api that currently exists should be stable. Tooling that uses it doesn't really exist beyond `Nullable/Nonnull` support that uses whatever rules they already had (meaning not the spec).

According to Spring an Nullaway (Uber) they are planning to use it, but that isn't there yet.

`Nullmarked` may not exist on a given class. If you put it on a package it's all classes in that package (non recursive). If you put it on a module (JPMS) it's all classes in the module. Which is the problem I can see for you... like you'd *always* have to inspect module/package/class for `Nullmarked` which is why you might want to comment to them, or come up with an API to specify that it is.

`Nullmarked` makes `NonNull` implicit, meaning it's always assumed to be there by default if `Nullable` isn't present.

`NotNull` explicitly that spelling is part of the Validation spec, and it is runtime an so very different. For equals you can't look at `NotNull` because it might be null at any given time, just not by the time validator is called.

**Comment by jqno** [comment]
Ah, so it's more like Eclipse's `@NonNullByDefault` annotation: https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm

EqualsVerifier supports it already for packages, so adding `@NullMarked` to that shouldn't be too hard.

Supporting it for modules might be a little harder, but I suppose I can look into it.

**Comment by xenoterracide** [comment]
Yeah spring has one for packages called nonnullAPI sorry speech to texting but that's spelled that way just slightly different casing

I wouldn't be surprised if you looked into it if eclipse was also looking at the Jspecify stuff. The alleged organization list was quite large.

**Comment by jqno** [comment]
You mean this one? https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullApi.html
I'll include that as well

**Comment by jqno** [comment]
I've just released version 3.16, which adds support for both `@NullMarked` and `@NonNullFields` (`@NonNullApi` is for APIs, so it doesn't apply for EqualsVerifier).

**Comment by xenoterracide** [comment]
btw, do you have support for the jakarta variants of the annotations. I'm mentally debating myself since I'm obsessively annotating anyways based on current tooling support for non null  as the default.

I like jspecify in principal but (slightly based on a comment on the spring thread) they kind of feel like a "me too" or "we have too many options, let's  make a standard" which results in a +1 option. I'm saying that based on some of my own thoughts regarding their lack of desire to support lazy init fields in 1.0, and apparently they removed the feature spring wanted (meta annotations that were present in jsr305).

**Comment by jqno** [comment]
If they have "normal" names like `@NotNull` or `@NonNull`, and `@Nullable`, then yes. Try it out and let me know if it works :)

**Comment by xenoterracide** [comment]
so... I realized I said that foolishly. As you should be ignoring `jakarta.validation` I was referring to `jakarta.annotation`. If you're not ignoring validation then I wonder what happens when I write `@Nullable` and `@NotNull` on the same thing... which is valid and not necessarily wrong. I'm assuming you've got that write, because I think we talked about it here even.
