### ISSUE TITLE
[Feature]  identify parent references in recurisive structures

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#937]
### Describe the feature

workaround is kind of obvious
```
java.lang.AssertionError: EqualsVerifier found a problem in class com.xenoterracide.jpa.FooAggregate.
-> Recursive datastructure.
Add prefab values for one of the following types: Set<BarEntity>, BarEntity, FooAggregate.
```

```java
  @Test
  void abstractAggregateEquality() {
    EqualsVerifier.forClass(FooAggregate.class)
      .withRedefinedSuperclass()
      .withPrefabValues(BarEntity.Id.class, BarEntity.Id.create(), BarEntity.Id.create())
      .withPrefabValues(FooAggregate.Id.class, FooAggregate.Id.create(), FooAggregate.Id.create())
      // .withPrefabValues(BarEntity.class, BarEntity.create(null, "bar"), BarEntity.create(null, "baz"))
      .suppress(Warning.SURROGATE_OR_BUSINESS_KEY)
      .withOnlyTheseFields("id", "version", "dirty")
      .verify();
  }
```

structure is basically 

foo.bar[].foo

each bar just has its own reference back to foo.

I'm not really worried given "withOnlyTheseFields".

### Describe the solution you'd like

Thought, provide a 2nd jar with an annotation to identify the parent reference. There may be other ways. This isn't a really high priority, just a thought. JPA also has it's whole "mappedBy" thing... maybe there could be a stringy API to do specify something goes back to parent, or even both.

### Additional context

This being a parent reference, there's not a good way for me to represent the real world here because I'd have to provide for both `FooAggregate` and `BarEntity`. We could talk about JPA specific solutions, but we both know there's databases that aren't JPA...

**Comment by jqno** [comment]
I'm sorry, I don't understand what you're asking here. What problem are you trying to solve?

> workaround is kind of obvious

Workaround for what?

> I'm not really worried given "withOnlyTheseFields".

How does `withOnlyTheseFields` factor into this?

**Comment by xenoterracide** [comment]
foo.bars.foo -> foo.bars.foo

foo == foo always, any case of not doing that is a bug somewhere (actually I have no idea if jpa or other systems would *actually* make it the same reference, but it should be)

it's a recursive structure but the reference to foo should always be the same, because it's a "parent node". I'm not worried about it because this structure isn't use in equality, but if it was this would be difficult, you'd actually have to provide both FooAggregate and BarEntity so that the reference would be the same, and not null.

**Comment by jqno** [comment]
I still don't understand what it is you're looking for. Can you please give a minimal reproducer (and I do mean minimal, so something I can paste directly into my editor and not have to fiddle with imports or attempt to read code that doesn't contribute to the problem) and try again?

**Comment by xenoterracide** [comment]
This is far simpler than anything I would even put an equals contract on. However, it occurs to me that it is the simplest reproduction. You see, a parent can never be anything but an existing reference.

In the real world example, since there's a package setter it *technically* can be, but that's just because hibernate.

Equalsverifier doesn't currently provide a way for me to say parent that parent is always the existing reference.

In my case what I'm actually doing is I have `Foo` as a root and `Bar` as children, and since equals doesn't actually look at children or parent, it doesn't matter so much. This demonstrates a scenario where I don't think equalsverifier currently could (completely) verify equality.

`EqualsVerifier.forClass(Node.class).verify()`

```java
static class Node {

    private final List<Node> children = new ArrayList<>();
    private Node parent;

    public List<Node> getChildren() {
      return Collections.unmodifiableList(children);
    }

    public Node getParent() {
      return parent;
    }

    void addChild(Node child) {
      this.children.add(child);
      child.parent = this;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (!(o instanceof Node node)) return false;
      return Objects.equals(children, node.children) && Objects.equals(parent, node.parent);
    }

    @Override
    public int hashCode() {
      return Objects.hash(children, parent);
    }
  }
```

**Comment by jqno** [comment]
Thanks for showing some code here. It looks like a classic case of recursive data structure. I get that in real life, the objects must be the same, but for the purpose of checking equals, it doesn't really matter if these internal class invariants actually hold. There are plenty of cases where EqualsVerifier breaks them, and it only starts mattering if the class starts throwing exceptions.

So, why would you want this feature? What problem does it solve?

**Comment by xenoterracide** [comment]
right, but, there's not a good way for me to provide an instance that of `FooAggregate` on `BarEntity` that isn't null. I guess I could, technically, but Foo isn't real world, I wrote it for testing, in the real world I'm likely to have more than one nested, and something I was testing out made it seem like that back reference was required in jpa for it to work. I'm probably more annoyed that I have to provide an instance. If there was more than 1, the amount of code I have to write for each scenario, although this is why we write "test data builders".

I guess I'm worried about the day this becomes a real problem, where the back reference to Foo can't be null.

**Comment by jqno** [comment]
I'm actually working on a smarter way to instantiate objects that should significantly reduce the need for `withPrefabValues`. Not sure yet if it'll help in your particular case, but one can hope. I think it will.

In the mean time, while I know that sometimes it can be hard to instantiate a class for use as a prefab value, remember that for EqualsVerifier, such a value doesn't actually need to be _valid_. Any reference will do. No need to represent the real world.

Also, if you're using EqualsVerifier in the first place, it probably means that you care about testing, so you probably already have ways of acquiring instances to plug into EqualsVerifier.
