### ISSUE TITLE
[Feature/Doc] Transient

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#939]
### Describe the bug

So, let's start with doc, there's no documentation for `Transient` https://jqno.nl/equalsverifier/errormessages/ ( did a ctrl+f )

For Feature. Per #935 I suggested that there has to be an in memory dirty tracking to avoid accidental missing updates when adding to a set

### Steps to reproduce

structures are here

https://github.com/xenoterracide/spring-app-commons/tree/test/equalsverifier/module/jpa/src/test/java/com/xenoterracide/jpa

### Error message and version number

```
java.lang.AssertionError: EqualsVerifier found a problem in class com.xenoterracide.jpa.FooAggregate.
-> Transient field dirty should not be included in equals/hashCode contract.

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
(EqualsVerifier 3.16, JDK 21.0.2 on Linux)
```

### Code: EqualsVerifier invocation

```java
    EqualsVerifier.forClass(FooAggregate.class)
      .withRedefinedSuperclass()
      .withPrefabValues(AbstractIdentity.class, FooAggregate.Id.create(), BarEntity.Id.create())
      .withPrefabValues(BarEntity.Id.class, BarEntity.Id.create(), BarEntity.Id.create())
      .withPrefabValues(FooAggregate.Id.class, FooAggregate.Id.create(), FooAggregate.Id.create())
      .withPrefabValues(BarEntity.class, BarEntity.create(null, "bar"), BarEntity.create(null, "baz"))
      .suppress(Warning.SURROGATE_OR_BUSINESS_KEY)
//      .suppress(Warning.TRANSIENT_FIELDS)
      .withOnlyTheseFields("id", "version", "dirty")
      .verify();
```

**Comment by jqno** [comment]
Sure, I can add a note for this specific error 👍🏼

**Comment by jqno** [comment]
Added a note to the website
