### ISSUE TITLE
What do I need to import?

### ISSUE THREAD

**Issue by spierepf** [jqno/equalsverifier#950]
### Describe the feature

None of the docs indicate the package I need to import in order to use EqualsVerifier.

All I ever get is
error: cannot find symbol EqualsVerifier.forClass(Pair.class).verify();

I have the library in my path, but I do not know what import statement to use:

12:38:45 a.m.: Executing 'dependencies'...

> Task :dependencies

------------------------------------------------------------
Root project 'SchemeInterpreter'
------------------------------------------------------------

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

compileClasspath - Compile classpath for source set 'main'.
No dependencies

compileOnly - Compile-only dependencies for the 'main' feature. (n)
No dependencies

default - Configuration for default artifacts. (n)
No dependencies

implementation - Implementation dependencies for the 'main' feature. (n)
No dependencies

mainSourceElements - List of source directories contained in the Main SourceSet. (n)
No dependencies

runtimeClasspath - Runtime classpath of source set 'main'.
No dependencies

runtimeElements - Runtime elements for the 'main' feature. (n)
No dependencies

runtimeOnly - Runtime-only dependencies for the 'main' feature. (n)
No dependencies

testAnnotationProcessor - Annotation processors and their dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
+--- org.junit:junit-bom:5.9.1
|    +--- org.junit.jupiter:junit-jupiter:5.9.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-api:5.9.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-params:5.9.1 (c)
|    \--- org.junit.platform:junit-platform-commons:1.9.1 (c)
+--- org.junit.jupiter:junit-jupiter -> 5.9.1
|    +--- org.junit:junit-bom:5.9.1 (*)
|    +--- org.junit.jupiter:junit-jupiter-api:5.9.1
|    |    +--- org.junit:junit-bom:5.9.1 (*)
|    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    +--- org.junit.platform:junit-platform-commons:1.9.1
|    |    |    +--- org.junit:junit-bom:5.9.1 (*)
|    |    |    \--- org.apiguardian:apiguardian-api:1.1.2
|    |    \--- org.apiguardian:apiguardian-api:1.1.2
|    \--- org.junit.jupiter:junit-jupiter-params:5.9.1
|         +--- org.junit:junit-bom:5.9.1 (*)
|         +--- org.junit.jupiter:junit-jupiter-api:5.9.1 (*)
|         \--- org.apiguardian:apiguardian-api:1.1.2
+--- org.mockito:mockito-core:5.11.0
|    +--- net.bytebuddy:byte-buddy:1.14.12
|    \--- net.bytebuddy:byte-buddy-agent:1.14.12
\--- nl.jqno.equalsverifier:equalsverifier:3.16.1

testCompileOnly - Compile only dependencies for source set 'test'. (n)
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
+--- org.junit:junit-bom:5.9.1 (n)
+--- org.junit.jupiter:junit-jupiter (n)
+--- org.mockito:mockito-core:5.11.0 (n)
\--- nl.jqno.equalsverifier:equalsverifier:3.16.1 (n)

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.junit:junit-bom:5.9.1
|    +--- org.junit.jupiter:junit-jupiter:5.9.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-api:5.9.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-params:5.9.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-engine:5.9.1 (c)
|    +--- org.junit.platform:junit-platform-commons:1.9.1 (c)
|    \--- org.junit.platform:junit-platform-engine:1.9.1 (c)
+--- org.junit.jupiter:junit-jupiter -> 5.9.1
|    +--- org.junit:junit-bom:5.9.1 (*)
|    +--- org.junit.jupiter:junit-jupiter-api:5.9.1
|    |    +--- org.junit:junit-bom:5.9.1 (*)
|    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    \--- org.junit.platform:junit-platform-commons:1.9.1
|    |         \--- org.junit:junit-bom:5.9.1 (*)
|    +--- org.junit.jupiter:junit-jupiter-params:5.9.1
|    |    +--- org.junit:junit-bom:5.9.1 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-api:5.9.1 (*)
|    \--- org.junit.jupiter:junit-jupiter-engine:5.9.1
|         +--- org.junit:junit-bom:5.9.1 (*)
|         +--- org.junit.platform:junit-platform-engine:1.9.1
|         |    +--- org.junit:junit-bom:5.9.1 (*)
|         |    +--- org.opentest4j:opentest4j:1.2.0
|         |    \--- org.junit.platform:junit-platform-commons:1.9.1 (*)
|         \--- org.junit.jupiter:junit-jupiter-api:5.9.1 (*)
+--- org.mockito:mockito-core:5.11.0
|    +--- net.bytebuddy:byte-buddy:1.14.12
|    +--- net.bytebuddy:byte-buddy-agent:1.14.12
|    \--- org.objenesis:objenesis:3.3
\--- nl.jqno.equalsverifier:equalsverifier:3.16.1

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
No dependencies

(c) - A dependency constraint, not a dependency. The dependency affected by the constraint occurs elsewhere in the tree.
(*) - Indicates repeated occurrences of a transitive dependency subtree. Gradle expands transitive dependency subtrees only once per project; repeat occurrences only display the root of the subtree, followed by this annotation.

(n) - A dependency or dependency configuration that cannot be resolved.

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 339ms
1 actionable task: 1 executed
12:38:46 a.m.: Execution finished 'dependencies'.

### Describe the solution you'd like

A doc with an import statement.

**Comment by jqno** [comment]
Oh no, I often complain about documentation and stackoverflow answers not mentioning what imports are needed to use something, and here I am doing the exact same thing on my site.

Thank you for bringing this to my attention. I've updated the README and the website.

For the record, you need `import nl.jqno.equalsverifier.*;`
