### ISSUE TITLE
[Bug] [FYI] Objenesis doesn't work properly if on a module path

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#985]
### Describe the bug

This is simply here to track an upstream bug https://github.com/easymock/objenesis/issues/332

### Steps to reproduce

I know, I know. This isn't a full reproducer, more of a ... maybe you can look at this and provide to them how it's being used, if you want... I believe all it really needs is this and to have a `module-info.java`

```java
 @Test
  void abstractAggregateEquality() {
    var fooId1 = FooAggregate.Id.create();
    var fooId2 = FooAggregate.Id.create();
    var barId1 = BarEntity.Id.create();
    var barId2 = BarEntity.Id.create();

    EqualsVerifier.forClass(FooAggregate.class)
      .withRedefinedSuperclass()
      .withPrefabValues(AbstractIdentitifier.class, barId1, fooId1)
      .withPrefabValues(BarEntity.Id.class, barId1, barId2)
      .withPrefabValues(FooAggregate.Id.class, fooId1, fooId2)
      .withPrefabValues(BarEntity.class, BarEntity.create(null, "bar"), BarEntity.create(null, "baz"))
      .withPrefabValues(
        DomainEvent.class,
        FooEvent.create(fooId1, new BarEntity.NameChanged(barId1, "foo")),
        FooEvent.create(fooId2, new BarEntity.NameChanged(barId2, "bar"))
      )
      .suppress(Warning.SURROGATE_OR_BUSINESS_KEY)
      .suppress(Warning.TRANSIENT_FIELDS)
      .withOnlyTheseFields("id", "version", "dirty")
      .verify();
  }
```

**Comment by jqno** [comment]
Thanks for the heads-up. I have dependabot set up for this repo so any update to objenesis will automatically make its way into EqualsVerifier. Closing.

**Comment by xenoterracide** [comment]
does make me curious, but I don't know when it was release. equalsverifier is only giving me version 3.3, but 3.4 is out. Unless there's been a major version bump of equalsverifier that I'm not getting.

**Comment by jqno** [comment]
Objenesis 3.4 was released after the most recent EqualsVerifier (as you can easily see on the respective Releases pages on github :wink:) 
If you want I can cut a release that includes the new objenesis.

**Comment by xenoterracide** [comment]
No, I was just... Checking while being lazy. I kind of assumed it was something like that. I tried the latest version. it didn't change anything on this for me.

**Comment by jqno** [comment]
I just released a new version with an updates Objenesis
